# Generated by Django 5.1.6 on 2025-02-12 12:33

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
from django.db.models import Q, CheckConstraint

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_managers_remove_user_last_name_user_dob_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # ... your Family and Grade models ...
        migrations.AddConstraint(
            model_name="user",
            constraint=CheckConstraint(
                check=~Q(email=models.F("email1")),  # Changed from 'condition' to 'check'
                name="email_email1_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=CheckConstraint(
                check=~Q(phone=models.F("phone1")),  # Changed from 'condition' to 'check'
                name="phone_phone1_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=CheckConstraint(
                check=~Q(username=models.F("reg_number")),  # Changed from 'condition' to 'check'
                name="username_regnumber_unique",
            ),
        ),

        migrations.AddField(
            model_name="family",
            name="mother",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]