# Generated by Django 5.1.6 on 2025-02-12 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_managers_remove_user_last_name_user_dob_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_name", models.CharField(max_length=100)),
                ("family_number", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Families",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_name", models.CharField(max_length=100)),
                ("admission_year_to_asyv", models.IntegerField()),
                ("graduation_year_to_asyv", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", models.F("email1")), _negated=True),
                name="email_email1_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone", models.F("phone1")), _negated=True),
                name="phone_phone1_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("username", models.F("reg_number")), _negated=True),
                name="username_regnumber_unique",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="mother",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
