# Generated by Django 5.1.6 on 2025-02-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_family_grade_user_email_email1_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to="api.grade",
            ),
        ),
    ]
