# Generated by Django 5.1.6 on 2025-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_family_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ep", models.CharField(max_length=100)),
                (
                    "leap_category",
                    models.CharField(
                        choices=[
                            ("science_center", "Science Center"),
                            ("art_center", "Art Center"),
                            ("sport", "Sport"),
                            ("club", "Club"),
                            ("professional", "Professional"),
                        ],
                        default="club",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
