# Generated by Django 5.1.6 on 2025-02-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_leap"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("EY", "EY"),
                            ("S4", "S4"),
                            ("S5", "S5"),
                            ("S6", "S6"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Combination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("combination_name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("credits", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_district", models.CharField(max_length=100)),
                ("origin_sector", models.CharField(max_length=100)),
                ("current_district_or_city", models.CharField(max_length=100)),
                ("current_county", models.CharField(max_length=100)),
                ("health_issue", models.TextField(blank=True, null=True)),
                ("marital_status", models.CharField(max_length=20)),
                ("life_status", models.CharField(max_length=20)),
                ("has_children", models.BooleanField()),
                (
                    "points_in_national_exam",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "maximum_points_in_national_exam",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("mention", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KidAcademics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.IntegerField()),
                (
                    "combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.combination",
                    ),
                ),
                (
                    "kid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academics",
                        to="api.kid",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.academiclevel",
                    ),
                ),
            ],
            options={
                "unique_together": {("kid", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="NationalSubjectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("S", "S"),
                            ("F", "F"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "kid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_results",
                        to="api.kid",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subject"
                    ),
                ),
            ],
            options={
                "unique_together": {("kid", "subject")},
            },
        ),
    ]
