# Generated by Django 5.1.6 on 2025-02-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_academiclevel_combination_subject_kid_kidacademics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kidacademics",
            name="level",
            field=models.CharField(
                choices=[("EY", "EY"), ("S4", "S4"), ("S5", "S5"), ("S6", "S6")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="kid",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kids",
                to="api.family",
            ),
        ),
        migrations.AddField(
            model_name="kid",
            name="graduation_status",
            field=models.CharField(
                choices=[
                    ("graduated", "Graduated"),
                    ("studying", "Studying"),
                    ("dropped", "Dropped"),
                    ("deceased_before", "Deceased Before Graduation"),
                ],
                default="studying",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="kid",
            name="leaps",
            field=models.ManyToManyField(related_name="kids", to="api.leap"),
        ),
        migrations.AddField(
            model_name="kid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="AcademicLevel",
        ),
    ]
