# Generated by Django 5.1.6 on 2025-03-05 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_kidacademics_level_kid_family_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^\\+?\\d{1,4}[\\d\\s()-]{7,15}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone1",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^\\+?\\d{1,4}[\\d\\s()-]{7,15}$"
                    )
                ],
            ),
        ),
    ]
