# Generated by Django 5.1.6 on 2025-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_user_phone_alter_user_phone1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
