# Generated by Django 5.1.6 on 2025-03-25 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_user_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^\\+?\\d{1,4}[\\d\\s()-]{7,30}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone1",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^\\+?\\d{1,4}[\\d\\s()-]{7,30}$"
                    )
                ],
            ),
        ),
    ]
