# Generated by Django 5.1.6 on 2025-05-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_user_is_alumni_user_is_crc_user_is_librarian_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_url",
            field=models.ImageField(
                default="profiles/default.jpeg", upload_to="profiles"
            ),
        ),
    ]
