# Generated by Django 5.1.6 on 2025-05-27 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_user_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="leap",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leap",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leap",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_leaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leap",
            name="leap_category",
            field=models.CharField(
                choices=[
                    ("science_center", "Science Center"),
                    ("art_center", "Art Center"),
                    ("sport", "Sport"),
                    ("club", "Club"),
                    ("programming", "Programming"),
                    ("professional", "Professional"),
                ],
                default="club",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "Full-time"),
                            ("P", "Part-time"),
                            ("S", "Self-employed"),
                            ("I", "Intern"),
                        ],
                        max_length=2,
                    ),
                ),
                ("industry", models.CharField(default="", max_length=2000)),
                ("description", models.CharField(default="", max_length=2000)),
                ("company", models.CharField(max_length=2000)),
                ("on_going", models.BooleanField(default=False)),
                ("crc_support", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.CharField(default="", max_length=100)),
                ("end_date", models.CharField(default="", max_length=100)),
                (
                    "alumn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employ",
                        to="api.kid",
                    ),
                ),
                (
                    "contributing_leaps",
                    models.ManyToManyField(
                        blank=True, related_name="related_employments", to="api.leap"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_employments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FurtherEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("C", "Certificate"),
                            ("A1", "Advanced diploma"),
                            ("A0", "Bachelors"),
                            ("M", "Masters"),
                            ("PHD", "PHD"),
                        ],
                        default="NMS",
                        max_length=3,
                    ),
                ),
                ("degree", models.CharField(max_length=2500)),
                ("university", models.CharField(max_length=2500)),
                ("country", models.CharField(max_length=200)),
                ("city", models.CharField(default="", max_length=200)),
                (
                    "scholarship",
                    models.CharField(
                        choices=[
                            ("F", "Full"),
                            ("P", "Partial"),
                            ("S", "Self-Sponsor"),
                        ],
                        max_length=3,
                    ),
                ),
                ("scholarship_details", models.CharField(default="", max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Dropped_Out"),
                            ("S", "Suspended"),
                            ("O", "On_going"),
                            ("C", "Completed"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "alumn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="studiedrafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
