# Generated by Django 5.1.6 on 2025-05-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_copy_kid_leap_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="kid",
            name="managed_leaps",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_kids",
                through="api.KidLeap",
                to="api.leap",
            ),
        ),
    ]
