# Generated by Django 5.1.6 on 2025-05-27 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_kid_managed_leaps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kid",
            name="leaps",
        ),
    ]
