# Generated by Django 5.1.6 on 2025-05-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_kid_leaps"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="kid",
            old_name="managed_leaps",
            new_name="leaps",
        ),
        migrations.RemoveField(
            model_name="furthereducation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="furthereducation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="furthereducation",
            name="university",
        ),
        migrations.AddField(
            model_name="furthereducation",
            name="application_result",
            field=models.CharField(
                choices=[
                    ("A", "Accepted"),
                    ("R", "Rejected"),
                    ("W", "Withdrow"),
                    ("P", "Pending"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="furthereducation",
            name="enrolled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="furthereducation",
            name="waitlisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="furthereducation",
            name="alumn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="studiedrafts",
                to="api.kid",
            ),
        ),
        migrations.AlterField(
            model_name="furthereducation",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Dropped_Out"),
                    ("S", "Suspended"),
                    ("O", "On_going"),
                    ("G", "Graduated"),
                    ("N", "NA"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="furthereducation",
            name="college",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="college",
                to="api.college",
            ),
        ),
    ]
