# Generated by Django 5.1.6 on 2025-06-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_college_rename_managed_leaps_kid_leaps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="furthereducation",
            name="crc_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="furthereducation",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="college",
                to="api.college",
            ),
        ),
        migrations.AlterField(
            model_name="furthereducation",
            name="level",
            field=models.CharField(
                choices=[
                    ("C", "Certificate"),
                    ("A1", "Advanced diploma"),
                    ("A0", "Bachelors"),
                    ("M", "Masters"),
                    ("PHD", "PHD"),
                ],
                default="C",
                max_length=3,
            ),
        ),
    ]
