# Generated by Django 5.2.1 on 2025-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_college_rename_managed_leaps_kid_leaps_and_more'),
    ]

    operations = [

    ]
