# Generated by Django 5.2.1 on 2025-06-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_furthereducation_crc_support_and_more'),
        ('api', '0019_remove_furthereducation_college_and_more'),
    ]

    operations = [
    ]
