# Generated by Django 5.2.1 on 2025-06-17 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20250605_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidacademics',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kidacademics',
            name='report_card',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='kidacademics',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='alumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment', to='api.kid'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='industry',
            field=models.CharField(choices=[('Agriculture, Forestry, and Fishing', 'Agriculture, Forestry, and Fishing'), ('Art, Design, and Performance', 'Art, Design, and Performance'), ('Beauty and Personal Care', 'Beauty and Personal Care'), ('Business and Management', 'Business and Management'), ('Construction and Engineering', 'Construction and Engineering'), ('Dining and Hospitality Services', 'Dining and Hospitality Services'), ('Education and Training', 'Education and Training'), ('Energy and Utilities', 'Energy and Utilities'), ('Finance and Banking', 'Finance and Banking'), ('Government and Public Service', 'Government and Public Service'), ('Healthcare and Medical Services', 'Healthcare and Medical Services'), ('Information Technology and Software Development', 'Information Technology and Software Development'), ('Legal Services', 'Legal Services'), ('Logistics and Transportation', 'Logistics and Transportation'), ('Manufacturing and Production', 'Manufacturing and Production'), ('Marketing, Sales, and Customer Service', 'Marketing, Sales, and Customer Service'), ('Media and Communication', 'Media and Communication'), ('Real Estate and Property Management', 'Real Estate and Property Management'), ('Research and Development', 'Research and Development'), ('Security and Law Enforcement', 'Security and Law Enforcement'), ('Social Work and Community Services', 'Social Work and Community Services'), ('Sports and Recreation', 'Sports and Recreation'), ('Telecommunications', 'Telecommunications'), ('Trade and Skilled Labor', 'Trade and Skilled Labor'), ('Others / Not Specified', 'Others / Not Specified')], default='Others / Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='furthereducation',
            name='alumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='furthereducation', to='api.kid'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kid', to=settings.AUTH_USER_MODEL),
        ),
    ]
