# Generated by Django 5.2.3 on 2025-06-24 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_remove_category_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="author_id",
        ),
    ]
