# Generated by Django 5.2.3 on 2025-07-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_author_author_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "in_short",
                    models.CharField(
                        help_text="A brief summary for the list view.", max_length=500
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("NW", "News"), ("AN", "Announcement")],
                        default="NW",
                        max_length=2,
                    ),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="news_media/")),
                ("is_image", models.BooleanField(default=False)),
                ("is_video", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "news_announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="api.newsannouncement",
                    ),
                ),
            ],
        ),
    ]
