# Generated by Django 5.2.1 on 2025-07-03 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_author_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=20000)),
                ('e_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='NMS', max_length=5000)),
                ('image_url', models.ImageField(default='events/default.jpg', upload_to='events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
