# Generated by Django 5.2.1 on 2025-07-06 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('op_type', models.CharField(default='Full Time', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('deadline', models.CharField(default='2024-08-23', max_length=1000)),
                ('link', models.CharField(default='asyv.ac.rw', max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('post_time', models.CharField(default='2025-07-06 09:16:35', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
