# Generated by Django 5.2.1 on 2025-07-08 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='post_time',
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
