# Generated by Django 5.2.1 on 2025-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_opportunity_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
