# Generated by Django 5.2.1 on 2025-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_opportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.CharField(default='asyv.ac.rw', max_length=200),
        ),
    ]
