# Generated by Django 5.2.1 on 2025-07-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_newsannouncement_mediafile'),
        ('api', '0029_alter_opportunity_link'),
    ]

    operations = [
    ]
