# Generated by Django 5.2.1 on 2025-07-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20250708_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='furthereducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
