# Generated by Django 5.2.1 on 2025-07-18 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_employment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
