# Generated by Django 5.2.1 on 2025-07-18 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_event_description_alter_event_e_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(default='events/default.jpg', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='NMS', max_length=5000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.CharField(default='asyv.ac.rw', max_length=200),
        ),
    ]
