# Generated by Django 5.2.1 on 2025-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_event_description_alter_event_e_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
