# Generated by Django 5.2.1 on 2025-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_opportunity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.CharField(default='ASYV', max_length=500),
        ),
    ]
