# Generated by Django 5.2.1 on 2025-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_opportunity_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(default='Kigali, Rwanda', max_length=500),
        ),
    ]
