--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2025-06-04 16:46:05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 258 (class 1259 OID 68813)
-- Name: api_college; Type: TABLE; Schema: public; Owner: postgres
--


DROP TABLE IF EXISTS public.api_college CASCADE;

CREATE TABLE public.api_college (
    id bigint NOT NULL,
    college_name character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    city character varying(100) NOT NULL
);


ALTER TABLE public.api_college OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 68812)
-- Name: api_college_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_college ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_college_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3404 (class 0 OID 68813)
-- Dependencies: 258
-- Data for Name: api_college; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_college (id, college_name, country, city) FROM stdin;
1	Abilene Christian University	United States	Abilene, Texas
2	Adventist University of Central Africa	Rwanda	Kigali
3	African Leadership University at Kigali	Rwanda	Kigali
4	African Leadership University-Mauritius	Mauritius	Pamplemousses
5	Agnes Scott College	United States	Decatur, Georgia
6	Akagera Aviation School	Rwanda	Kigali
7	Akilah Institute for Women	Rwanda	Kigali
8	Alibaba University	China	Hangzhou
9	Arab-Emirates University	United Arab Emirates	Al Ain
10	ARDEN University	United Kingdom	Coventry, England
11	Arizona State University	United States	Tempe, Arizona
12	Ashesi University	Ghana	Berekuso
13	Atlantic International University	United States	Honolulu, Hawaii
14	Bates College	United States	Lewiston, Maine
15	Birmingham Southern College/University of California, Berkeley	United States	Berkeley, California
16	Brown University	United States	Providence, Rhode Island
17	Carnegie Mellon University Africa	Rwanda	Kigali
18	Catholique University of Rwanda	Rwanda	Huye
19	Cavendish University	Zambia	Lusaka
20	Christian University of Rwanda	Rwanda	Kigali
21	College of Baltimore Country	United States	Baltimore County, Maryland
22	Colon Language Center	Germany	Hamburg
23	Columbia College Chicago	United States	Chicago, Illinois
24	Darsalma Maritime Institute	Tanzania	Dar Es Salaam
25	Davis College	Rwanda	Kigali
26	Earth University-Costa Rica, Agricultural Science	Costa Rica	San José
27	East African Christian College	Rwanda	Kabuga
28	East African University of Rwanda	Rwanda	Nyagatare
29	Edinburgh University	Scotland	Edinburgh
30	Emory University-Atlanta	United States	Atlanta, Georgia
31	Ethiopia Airforce Engineering College	Ethiopia	Addis Ababa
32	Great Lakes Hopitality Institute	Rwanda	Kigali
33	Hendrix College	United States	Conway, Arkansas
34	Independent University of Kigali	Rwanda	Kigali
35	Institut Superieur Doctorate of Business Administration	France	Paris
36	Institute Catholique de Kabgayi	Rwanda	Muhanga
37	Institute of Agriculture Technology and Education	Rwanda	Ngoma
38	Institute of Applied Sciences	Rwanda	Ruhengeri
39	Institute of Lay Adventists of Kigali	Rwanda	Kigali
40	Integrated Polytechnic Regional Centre	Rwanda	Kigali
41	Interdisciplinary Center Herzliya	Israel	Herzliya
42	Kabgayi Seminar	Rwanda	Muhanga
43	Keiser University	United States	Fort Lauderdale, Florida
44	Kenya Utalii University	Kenya	Nairobi
45	Kepler University	Rwanda	Kigali
46	Kigali Institute of Management	Rwanda	Kigali
47	Kwame Nkrumah University	Zambia	Kabwe
48	Lanzhou University	China	Lanzhou
49	Lovely Professional University	India	Phagwara, Punjab
50	Luxembourg University	Luxembourg	Luxembourg City
51	Makerere University	Uganda	Kampala
52	Marist College	United States	Poughkeepsie, New York
53	McGill University	Canada	Montreal
54	Minerva University	United States	San Francisco, California
55	Mount Kenya University	Kenya	Thika
56	Mount Kigali University	Rwanda	Kigali
57	Muhlenburg College	United States	Allentown, Pennsylvania
58	Oklahoma Christian University	United States	Edmond, Oklahoma
59	Pandit Deendayal Energy University	India	Gandhinagar, Gujarat
60	Protestant School of Art & Social Science	Rwanda	Huye
61	Qinzhou University	China	Qinzhou
62	Quest University	Canada	Squamish, British Columbia
63	RICA (Rwanda Institute for Conservation Agriculture)	Rwanda	Gashora
64	Rochester University	United States	Rochester, New York
65	Rwanda Military Academy	Rwanda	Gako
66	Rwanda Nation Police	Rwanda	Kigali
67	Saint Joseph Integrated School	Rwanda	Kigali
68	Seton Hill University	United States	Greensburg, Pennsylvania
69	Smith College	United States	Northampton, Massachusetts
70	Southern Maine College	United States	Maine
71	Southern New Hampshire University	United States	Manchester, New Hampshire
72	St Joseph Integrated	Rwanda	Kigali
73	St Lawrence University	United States	Canton, New York
74	Texas Christian University	United States	Fort Worth, Texas
75	Tufts University	United States	Medford, Massachusetts
76	Uni Camillus Medical University	Italy	Rome
77	United States International University Africa	Kenya	Nairobi
78	University of British Colombia	Canada	Vancouver
79	University of Gitwe	Rwanda	Gitwe
80	University of Global Health Equity	Rwanda	Kigali
81	University of Houston	United States	Houston, Texas
82	University of Kigali	Rwanda	Kigali
83	University of Lay Adventists of Kigali	Rwanda	Kigali
84	University of Lincoln Nebraska	United States	Lincoln, Nebraska
85	University of Pennsylvania  (British Colombia)	United States	Philadelphia, Pennsylvania
86	University of Rochester	United States	Rochester, New York
87	University of Rwanda	Rwanda	Kigali
88	University of Tourism, Technology and Business Studies	Rwanda	Kigali
89	University of Warsaw of Business	Poland	Warsaw
90	University of Wisconsin-Madison	United States	Madison, Wisconsin
91	VATEL Rwanda( International Hospitality Management School Vatel)	Rwanda	Kigali
92	Vistula University	Poland	Warsaw
93	Washington and Lee University	United States	Lexington, Virginia
94	Westmont College	United States	Montecito, California
95	WSB Poznan University	Poland	Poznań
96	Yale University	United States	New Haven, Connecticut
\.


--
-- TOC entry 3410 (class 0 OID 0)
-- Dependencies: 257
-- Name: api_college_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_college_id_seq', 96, true);


--
-- TOC entry 3260 (class 2606 OID 68817)
-- Name: api_college api_college_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_college
    ADD CONSTRAINT api_college_pkey PRIMARY KEY (id);


-- Completed on 2025-06-04 16:46:05

--
-- PostgreSQL database dump complete
--

