--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2025-05-28 15:13:33

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 240 (class 1259 OID 52272)
-- Name: api_combination; Type: TABLE; Schema: public; Owner: postgres
--

DROP TABLE IF EXISTS public.api_combination CASCADE;

CREATE TABLE public.api_combination (
    id bigint NOT NULL,
    combination_name character varying(100) NOT NULL,
    abbreviation character varying(20) NOT NULL
);


ALTER TABLE public.api_combination OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 52271)
-- Name: api_combination_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_combination ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_combination_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3404 (class 0 OID 52272)
-- Dependencies: 240
-- Data for Name: api_combination; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_combination (id, combination_name, abbreviation) FROM stdin;
6	Mathematics, Chemistry and Biology	MCB
7	Mathematics, Computer Science and Economics	MCE
8	Mathematics, Economics and Geography	MEG
10	Mathematics, Physics and Computer Science	MPC
11	Physics, Chemistry and Biology	PCB
1	Mathematics, Physics and Computer Science	MPC
2	English, French and Kinyarwanda	EFK
3	History, Economics and Geography	HEG
4	History, Economics and Literature in English	HEL
5	Literature in English, French and Kinyarwanda	LFK
\.


--
-- TOC entry 3410 (class 0 OID 0)
-- Dependencies: 239
-- Name: api_combination_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_combination_id_seq', 11, true);


--
-- TOC entry 3260 (class 2606 OID 52276)
-- Name: api_combination api_combination_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_combination
    ADD CONSTRAINT api_combination_pkey PRIMARY KEY (id);


-- Completed on 2025-05-28 15:13:33

--
-- PostgreSQL database dump complete
--

