--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2025-06-03 16:49:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 250 (class 1259 OID 68732)
-- Name: api_employment; Type: TABLE; Schema: public; Owner: postgres
--
DROP TABLE IF EXISTS public.api_employment CASCADE;

CREATE TABLE public.api_employment (
    id bigint NOT NULL,
    title character varying(5000) NOT NULL,
    status character varying(2) NOT NULL,
    industry character varying(2000) NOT NULL,
    description character varying(2000) NOT NULL,
    company character varying(2000) NOT NULL,
    on_going boolean NOT NULL,
    crc_support boolean NOT NULL,
    is_approved boolean NOT NULL,
    approved_at timestamp with time zone,
    start_date character varying(100) NOT NULL,
    end_date character varying(100) NOT NULL,
    alumn_id bigint NOT NULL,
    recorded_by_id bigint
);


ALTER TABLE public.api_employment OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 68731)
-- Name: api_employment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_employment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_employment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3408 (class 0 OID 68732)
-- Dependencies: 250
-- Data for Name: api_employment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_employment (id, title, status, industry, description, company, on_going, crc_support, is_approved, approved_at, start_date, end_date, alumn_id, recorded_by_id) FROM stdin;
1	Waiter	F	Business		1000Hills Hotel	f	f	f	\N			2057	\N
2	Waiter	F	Hospitality		1000Hills Hotel	f	f	f	\N			2428	\N
3	Loan officer	F	Banking		AB Bank	f	f	f	\N			110	\N
4	Cashier	F	Hospitality		Abanan Pack Hotel- Kimironko	f	f	f	\N			705	\N
5	Cashier	F	Banking		Acces bank	f	f	f	\N			109	\N
6	Corporate officer in Digital Learning	F	IT		Accor in Dubai	f	f	f	\N			10	\N
7	Academic Tutor and Advise	F	Education		Admission Counselor of Atlantic Kigali Randa	f	f	f	\N			575	\N
8	Coordinator	F	Managemet		Aegis Trust	f	f	f	\N			36	\N
9	Data Entry Cleck	F	Managemet		Aegis Trust	f	f	f	\N			2451	\N
10	Youth Education Officer	F	Education		AER Project	f	f	f	\N			2395	\N
11	Photographer and Video Edite	F	Art		Africa Digital Media	f	f	f	\N			1502	\N
12	Technologist	F	Technologist		Africa Improved Food Ltd	f	f	f	\N			2151	\N
13	Student Life Associate	F	Education		African Leadership University	f	f	f	\N			1855	\N
14	IT Manager	F	Technology		Afrinest Engineering Ltd	f	f	f	\N			120	\N
15	Accountant officer	F	Business		Afrinest Group  Rwanda	f	f	f	\N			2108	\N
16	Surveyor Team	F	Construction		Afrinest Group Rwanda	f	f	f	\N			2138	\N
17	Cashier	F	Business		Afro beat	f	f	f	\N			2518	\N
18	Causul Worker	F	Business		Agahozo-Shalom Youth Village	f	f	f	\N			2017	\N
19	Logistic officer	F	Business		Agahozo-Shalom Youth Village	f	f	f	\N			1956	\N
20	Academic Advisor in Mathematic	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2178	\N
21	Academic Advisor in Social Science	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1614	\N
22	Administrator	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2477	\N
23	Agahozo-Shalom Youth Village	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2285	\N
24	Art Intern	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2044	\N
25	Assistant Teacher	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1837	\N
26	ASYV- Math Academic Advisor	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			620	\N
27	ASYV-Debate Intern	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1864	\N
28	ASYV-IT	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			655	\N
29	ASYV-Science Academic Advisor	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1543	\N
30	ASYV-Socail Science Academic Advisor	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2103	\N
31	ASYV-Social Science Academic  Advisor	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1817	\N
32	Cashier	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			168	\N
33	Casual Worker	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1618	\N
34	Casual worker	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1635	\N
35	Causal worker	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			664	\N
36	Debate Club	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1447	\N
37	IT Assistant	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			121	\N
38	IT School Assisant	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2513	\N
39	LEAP Manager	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			35	\N
40	Librarian and Teacher Intern	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1928	\N
41	Logistic officer	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1786	\N
42	Media Center	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1670	\N
43	Music Production	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			682	\N
44	Parental Wholeness	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2333	\N
45	Payton	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1685	\N
46	Payton	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2172	\N
47	Professional Internship	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			638	\N
48	Science Center	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1788	\N
49	Science Center	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1576	\N
50	Science Center	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1785	\N
51	Security officer	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1824	\N
52	Security officer	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2470	\N
53	Social Scienne-Academic Advisor	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			621	\N
54	Visit Intern	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			1668	\N
55	Visit Intern	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2435	\N
56	Health care Management and Administrative Assistant	F	Healthcare and Health Promotion		Agahozo-Shalom Youth Village	f	f	f	\N			2137	\N
57	Visitor Services Officer	F	Hospitality		Agahozo-Shalom Youth Village	f	f	f	\N			574	\N
58	Agahozo - Shalom Youth Village	F	IT		Agahozo-Shalom Youth Village	f	f	f	\N			1950	\N
59	Security officer	F	Security		Agahozo-Shalom Youth Village	f	f	f	\N			2279	\N
60	Sewing Officer	F	Sewing		Agahozo-Shalom Youth Village	f	f	f	\N			2347	\N
61	Security	F	Security		Agaposo Security Ltd	f	f	f	\N			2092	\N
62	CEO	F	Management		Agri-Business	f	f	f	\N			2216	\N
63	Selling Officer	F	Agribusiness		Agrimedical-Business	f	f	f	\N			1616	\N
64	Business Trainer	F	Business		AIESEC	f	f	f	\N			1737	\N
65	Medical technician	F	Military		Air Force	f	f	f	\N			1857	\N
66	Call center	F	Business		Airtel Rwanda	f	f	f	\N			152	\N
67	Saler officer	F	Business		Airticket saler	f	f	f	\N			732	\N
68	Business Development officer	F	Business		Akagera Aviation	f	f	f	\N			113	\N
69	Marketing Manager	F	Business		Alliance Group	f	f	f	\N			1902	\N
70	United States, Colorado	F	Healthcare and Health Promotion		Am a CNA Nurse	f	f	f	\N			1574	\N
71	Transilator	F	Communication		Amakoro Songa Africa	f	f	f	\N			693	\N
72	Basketball Player	F	Education		Basketball Player	f	f	f	\N			1734	\N
73	Inventor officer	F	Business		Ameki Colour	f	f	f	\N			1468	\N
74	Marketing	F	Business		Ameki Colour	f	f	f	\N			1974	\N
75	Customer Care	F	Hospitality		Ampersand Rwanda	f	f	f	\N			124	\N
76	Supervisor	F	Education		ANSPPLUS	f	f	f	\N			734	\N
77	Betting	F	Business		Gravictory Ltd	t	f	f	\N			1740	\N
78	Army	F	Military		Army	f	f	f	\N			1959	\N
79	Army	F	Security		Army	f	f	f	\N			2479	\N
80	Marine  Soldier	F	Security		Army	f	f	f	\N			2287	\N
81	Customer care	F	Hospitality		Art Unumuntu	f	f	f	\N			1623	\N
82	Sales and Marketing	F	Hospitality		Ashel tour Ltd	f	f	f	\N			2048	\N
83	Student Relations Coordinator, Special Projects	F	Education		Ashinaga Foundation	f	f	f	\N			1565	\N
84	Waiter	F	Hospitality		Asie Kitcken	f	f	f	\N			50	\N
85	Accommodations Officer	F	Education		ASYV- Hospitality	f	f	f	\N			2270	\N
86	Cooker	F	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2162	\N
87	Inkomoko	F	Technology		AT&T	f	f	f	\N			2329	\N
88	Data Entry Cleck	F	Technology		Audit Campany Ltd	f	f	f	\N			577	\N
89	Human Ressources Officer	F	Business		Auditing Firm	f	f	f	\N			1471	\N
90	Counselar officer	F	Education		Avega Agahozo	f	f	f	\N			1609	\N
91	Cashier	F	Business		B.Maurice Guest house	f	f	f	\N			1641	\N
92	Hospitality	F	Hospitality		Amazing Africa Eco-Tours	f	f	f	\N			2478	\N
93	Cashier	F	Business		Bank of Kigali	f	f	f	\N			606	\N
94	Secretary of CEO in Bank of Kigali	F	Business		Bank of Kigali	f	f	f	\N			2229	\N
95	Senior Client Service representantive	F	Banking		Bank of New York Mellon -Poland	f	f	f	\N			111	\N
96	Customer care	F	Business		Bar	f	f	f	\N			1996	\N
97	Receptionist	F	Hospitality		B-boby Health Care (Call Center)	f	f	f	\N			727	\N
98	Marketing officer at Muhanga	F	Business		BBOX Solar Power	f	f	f	\N			1753	\N
99	Call center	F	Hospitality		BBOX Solar Power	f	f	f	\N			45	\N
100	Call Operator	F	Business		BBOXX CAPITAL RWANDA	f	f	f	\N			2393	\N
101	Waiter	F	Hospitality		Beach Hotel Muhazi	f	f	f	\N			1497	\N
102	Customer care	F	Business		Beeting Campany/ Kanombe	f	f	f	\N			1911	\N
103	Customer care	F	Business		Betting Campany	f	f	f	\N			1619	\N
104	Receptionist	F	Hospitality		Betting Sport at Masaka	f	f	f	\N			1755	\N
105	Receptionist	F	Business		Betting Sport at Muhanga	f	f	f	\N			2336	\N
106	IT Officer	F	Education		BF SUMA	f	f	f	\N			1645	\N
107	Lab technician	F	Healthcare and Health Promotion		Biotechnician/ Liege	f	f	f	\N			2263	\N
108	Waiter	F	Hospitality		Biryogo Restaurant	f	f	f	\N			2500	\N
109	Store Assistant	F	Business		Blarirwa Ltd	f	f	f	\N			68	\N
110	OFAC Specialist	F	Business		BNP Paribas	f	f	f	\N			2075	\N
111	Store keeper	F	Construction		Bonus Industriel	f	f	f	\N			737	\N
112	Story telling and Communication	F	Communication		Bookmobile	f	f	f	\N			1449	\N
113	Story telling and Communication	F	Communication		Bookmobile	f	f	f	\N			1474	\N
114	Waiter	F	Business		Boutique	f	f	f	\N			2402	\N
115	Self-Employed	F	Business		Boutique-Shop	f	f	f	\N			692	\N
116	Business Developer and Financial Analyst	F	Business		BPN	f	f	f	\N			1973	\N
117	Loan Officer	F	Business		Brac Ltd Bank	f	f	f	\N			2503	\N
118	Custome service	F	Banking		BRAC Rwanda	f	f	f	\N			1637	\N
119	Credit Officer	F	Business		BRAC Rwanda	f	f	f	\N			613	\N
120	Cashier	F	Business		Brac Rwanda Microfinance	f	f	f	\N			694	\N
121	Waiter	F	Business		Brioche	f	f	f	\N			718	\N
122	Commis Chief	F	Business		Brioche Ltd/Cullinary Art	f	f	f	\N			698	\N
123	Journalist	F	Journalist		BTN Television	f	f	f	\N			2183	\N
124	District Field Officer	F	Managemet		Bufmar Enabel Health Project	f	f	f	\N			610	\N
125	Primary Teacher	F	Education		Busasamana Primary School	f	f	f	\N			148	\N
126	Customer care	F	Business		Business	f	f	f	\N			2348	\N
127	Canal Puls	F	Selling Officer		Business	f	f	f	\N			1908	\N
128	Waiter	F	Hospitality		Camelia Restaurant	f	f	f	\N			1500	\N
129	headwaitress	F	Business		Camellia Coffe shop	f	f	f	\N			2123	\N
130	Waiter	F	Business		Camellia Coffe shop	f	f	f	\N			1989	\N
131	Cashier	F	Business		Canal Puls	f	f	f	\N			2218	\N
132	Call Center	F	Hospitality		Cash Rwanda	f	f	f	\N			603	\N
133	Social Worker	F	Education		CECYDAR	f	f	f	\N			1976	\N
134	Service Administrator/Sales and Marketing	F	Business		CFAO Motors Rwanda (Dealer of Volkswagen)	f	f	f	\N			2030	\N
135	Agahozo-Shalom Youth Village	F	Education		Charge of Sport and Club	f	f	f	\N			1559	\N
136	Store keeper	F	Hospitality		Chez Lando	f	f	f	\N			2485	\N
137	Making Baker	F	Hospitality		Chill Motel	f	f	f	\N			656	\N
138	Driver	F	Construction		Chillngton Ltd	f	f	f	\N			1943	\N
139	Driver	F	Business		China Load	f	f	f	\N			1865	\N
140	Mraketing Consulting & Customer Service	F	Business		Choice Africa Investment	f	f	f	\N			2015	\N
141	Care giver	F	Healthcare and Health Promotion		Chrysalis	f	f	f	\N			1952	\N
142	Intern(Nurse)	F	Healthcare and Health Promotion		CHUK	f	f	f	\N			2182	\N
143	Waiter	F	Business		CHUK Restaurant	f	f	f	\N			1622	\N
144	Communicaation Officer	F	Education		Cindy Foundation	f	f	f	\N			49	\N
145	Photography	F	Art		Cinematograph-Huye	f	f	f	\N			1841	\N
146	ASSS	F	Business		CIUSSS	f	f	f	\N			2323	\N
147	Cashier	F	Business		Coast Freight Forwarder Agency Ltd	f	f	f	\N			1664	\N
148	Librarian	F	Education		College Saint Marie Kibuye	f	f	f	\N			1934	\N
149	Accountant officer	F	Business		Computer Campany Ltd	f	f	f	\N			1512	\N
150	IT Manager	F	Technology		Consultanty Campany	f	f	f	\N			37	\N
151	Accountant officer	F	Business		Consulting Up Paris	f	f	f	\N			2385	\N
152	Volontialism	F	Healthcare and Health Promotion		Corps Africa	f	f	f	\N			2494	\N
153	Customer care	F	Business		Costometic Business	f	f	f	\N			2281	\N
154	Logistic Manager	F	Business		Country hardware	f	f	f	\N			2383	\N
155	Social Worker	F	Healthcare and Health Promotion		Cree Board of Health and Social Service	f	f	f	\N			118	\N
156	Saler officer	F	Business		Crepe House cooking	f	f	f	\N			143	\N
157	Hospitality	F	Hospitality		King Faisal Hospital	t	f	f	\N			589	\N
158	Presales Engineer	F	Technology		Dat stream-Network and Cybersecurity	f	f	f	\N			2214	\N
159	IT Software	F	Technology		Data Software Campany	f	f	f	\N			2257	\N
160	care giver	F	Healthcare and Health Promotion		Delight AFC	f	f	f	\N			2467	\N
161	Customer Support Executive	F	IT		Deriv Rwanda ltd.	f	f	f	\N			1688	\N
162	Receptionist	F	Telecommunication		DHL German Logisitic Campany	f	f	f	\N			1515	\N
163	Administrator Assistant	F	Business		DICo Ltd	f	f	f	\N			2105	\N
164	Driver	F	Business		Discovery Go Africa	f	f	f	\N			2243	\N
165	Teacher Assistant	F	Education		discovery international school	f	f	f	\N			2016	\N
166	Surveyor	F	Construction		DONGIL Construction	f	f	f	\N			597	\N
167	Customer Care	F	Business		DP World Kigali @ Masaka	f	f	f	\N			1886	\N
168	Warehouse officer	F	Business		DP World Kigali @ Masaka	f	f	f	\N			51	\N
169	Driver	F	Business		Driver	f	f	f	\N			1853	\N
170	Customer care	F	Hospitality		Dubai Hotel	f	f	f	\N			2298	\N
171	Waiter	F	Hospitality		Dubai Hotel	f	f	f	\N			2422	\N
172	Senior Technical Officer in Charge of Post Clearance Audit	F	Business		Dubai Port World	f	f	f	\N			1883	\N
173	Logistic officer	F	Construction		Duo Corporation	f	f	f	\N			2258	\N
174	Sales and Marketing	F	Business		Dynamic Business Group Ltd	f	f	f	\N			1679	\N
175	Cashier	F	Hospitality		E&food	f	f	f	\N			134	\N
176	Primary Teacher	F	Education		E.P Gahondo -Gakenke	f	f	f	\N			728	\N
177	Teacher - Burera District	F	Education		E.S Kananga	f	f	f	\N			1876	\N
178	Card operations  Officer	F	Business		Ecobank	f	f	f	\N			2031	\N
179	House keeping Officer	F	Hospitality		La Palise Hotel Nyamata	t	f	f	\N			41	\N
180	Trainer Officer	F	Education		Educate/Akazi Kanoze	f	f	f	\N			1639	\N
181	Training Officer	F	Education		Educate/Akazi Kanoze	f	f	f	\N			1890	\N
182	Data Entry Cleck	F	Technology		Ejo-Heza	f	f	f	\N			2264	\N
183	Finance Officer	F	Business		ELPROMACO LTd	f	f	f	\N			2413	\N
184	Photographer	F	Art		Envision Rwanda	f	f	f	\N			2034	\N
185	Photographer/Video Grapher	F	Art		Envision Rwanda	f	f	f	\N			2040	\N
186	Photographer	F	Business		Envision Rwanda	f	f	f	\N			1843	\N
187	Waiter	F	Business		Envision Rwanda	f	f	f	\N			2337	\N
188	Waiter	F	Hospitality		Envision Rwanda	f	f	f	\N			1847	\N
189	Waiter	F	Hospitality		Envision Rwanda	f	f	f	\N			2444	\N
190	House keeping supervisor	F	Hospitality		Marriot Hotel	t	f	f	\N			2184	\N
191	Teacher	F	Education		EP GITARAGA	f	f	f	\N			2186	\N
192	Teacher	F	Education		EP Jeunesse	f	f	f	\N			128	\N
193	Business Developer and Financial Analyst	F	Business		EPC AFRICA Group	f	f	f	\N			2097	\N
194	Marketing officer	F	Business		Equit Bank	f	f	f	\N			609	\N
195	Cashier	F	Banking		Equity Bank	f	f	f	\N			2454	\N
196	Records management officer	F	Business		Equity Bank	f	f	f	\N			2120	\N
197	IT Data	F	Technology		Ernest&Ltd Consultant	f	f	f	\N			1858	\N
198	Tax Officer	F	Accounting		Ernst & Young Rwanda	f	f	f	\N			584	\N
199	Retails officer	F	Business		ES I rugwagwa	f	f	f	\N			1743	\N
200	Numerate Officer	F	Technology		Ethical Research Solution Ltd	t	f	f	\N			1658	\N
201	Logistic officer	F	Business		Excella Produce Ltd	t	f	f	\N			1748	\N
202	Causal worker	F	Business		F&D company	t	f	f	\N			1933	\N
203	Manifacture	F	Business		F&D company	t	f	f	\N			651	\N
204	F&D company	F	Manifacture		F&D company	t	f	f	\N			654	\N
205	Professional Internship	F	Management		F&D company	t	f	f	\N			646	\N
206	F&D company	F	Technicien		F&D company	t	f	f	\N			649	\N
207	Coacher	F	Art		FERWABA	t	f	f	\N			2117	\N
208	Sales and Marketing Executive	F	Business		Fine furniture ltd	t	f	f	\N			1697	\N
209	Front Desk Agent Manager	F	Hospitality		Five Dubai Hotel	t	f	f	\N			2359	\N
210	Cabin Crew	F	Sport		Flight operations/cabin crew	t	f	f	\N			1760	\N
211	Cashier	F	Business		Food Supply -Kacyiru	t	f	f	\N			1869	\N
212	Customer Care	F	Hospitality		Footbeting	t	f	f	\N			16	\N
213	Waiter	F	Hospitality		Four Point- Sherton Hotel	t	f	f	\N			64	\N
214	Waiter	F	Hospitality		Four Points by Sheraton	t	f	f	\N			1601	\N
215	Receptionist	F	Hospitality		Four Points by Sheraton Kigali	t	f	f	\N			1926	\N
216	Room service	F	Hospitality		Four points by Sheraton kigali	t	f	f	\N			13	\N
217	Camera men	F	Business		Freelance	t	f	f	\N			57	\N
218	Assistant	F	Administrator		Fruit corner ltd	t	f	f	\N			2394	\N
219	Accountant officer	F	Business		Fuel Station	t	f	f	\N			2227	\N
220	Cashier	F	Education		G.S Gasaka	t	f	f	\N			1473	\N
221	Teacher Assistant	F	Education		G.S Kibirizi	t	f	f	\N			594	\N
222	Teacher	F	Education		G.S Kinihira	t	f	f	\N			123	\N
444	Army	F	Security		Rwanda Defence Forces	t	f	f	\N			119	\N
223	Teacher Assistant	F	Education		G.S Kora Catholic	t	f	f	\N			1657	\N
224	Biology Teacher	F	Education		G.S Munini	t	f	f	\N			1501	\N
225	Teacher	F	Education		G.S Mwulire	t	f	f	\N			1903	\N
226	Teacher Assistant	F	Education		G.S Sasabirago	t	f	f	\N			1591	\N
227	Cashier	F	Business		Gacuriro- Sac Shop	t	f	f	\N			2204	\N
228	Security officer	F	Security		Gardaworld company	t	f	f	\N			1656	\N
229	Nurse	F	Healthcare and Health Promotion		Gatagara Hospital District	t	f	f	\N			1534	\N
230	journalist	F	Education		GC Nyinawajambo Ruhita	t	f	f	\N			2415	\N
231	Supervisor	F	Education		GI group	t	f	f	\N			1592	\N
232	Teacher	F	Education		Gihara Primary School	t	f	f	\N			2121	\N
233	IT Teacher	F	Education		GIHEKE TECHNICAL SECONDARY SCHOOL	t	f	f	\N			115	\N
234	Script writter/drammer actor	F	Art		Girl Effect	t	f	f	\N			9	\N
235	Dentist Nursing	F	Healthcare and Health Promotion		Gisagara Health Center	t	f	f	\N			166	\N
236	Teacher	F	Education		Gishari Nursery School	t	f	f	\N			126	\N
237	Data officer	F	Education		Global Community	t	f	f	\N			39	\N
238	Finance Manager	F	Business		Globl East Africa Ltd/Travel programs that focuses on hands on educational experiences.	t	f	f	\N			2491	\N
239	Administrator Officer	F	Hospitality		Go-Discovery Africa	t	f	f	\N			1588	\N
240	Cashier	F	Business		Good Life Supermarket	t	f	f	\N			1835	\N
241	Client relationshhip manager	F	Hospitality		Gotis ltd	t	f	f	\N			2432	\N
242	Client relationshhip manager	F	Hospitality		Gotis ltd	t	f	f	\N			2380	\N
243	Cooker	F	Hospitality		Radisson Blu Hotel	t	f	f	\N			2311	\N
244	Boarding Supervisor	F	Education		Green Hills Academy	t	f	f	\N			153	\N
245	Marketing officer	F	Business		Greenroad	t	f	f	\N			2488	\N
246	Teacher	F	Education		Group Scolaire Kanyinya	t	f	f	\N			2448	\N
247	Administrator Senior Officer	F	Education		Groupe Scolaire de Don Bosco Kicukiro	t	f	f	\N			2206	\N
248	IT Teacher	F	Education		Groupe Scolaire Kabare	t	f	f	\N			40	\N
249	Project Manager	F	Education		Grow Movement	t	f	f	\N			1643	\N
250	Teacher	F	Education		GS Byumba	t	f	f	\N			772	\N
251	Teacher	F	Education		GS Nyagasambu	t	f	f	\N			2192	\N
252	Teacher Geo/Entre	F	Education		GS Rwasa	t	f	f	\N			1597	\N
253	Cashier	F	Banking		GT Bank - Ngoma Branch	t	f	f	\N			1728	\N
254	Software Developer	F	Technology		GTBANK Rwanda PLC	t	f	f	\N			1653	\N
255	Bank teller	F	Business		Guaranty Trust Bank GT Co	t	f	f	\N			809	\N
256	Security Guard	F	Security		Guards Word Security	t	f	f	\N			2160	\N
257	Accountant officer	F	Business		Guestpro Tours Ltd	t	f	f	\N			1762	\N
258	Hostess	F	Hospitality		The Warner Brothers Hotel	t	f	f	\N			136	\N
259	Customer Care	F	Business		Hardware at Kimironk	t	f	f	\N			1842	\N
260	Saler officer	F	Business		Hardware at Kimironk	t	f	f	\N			2515	\N
261	Cashier	F	Business		Hardware Bugesera	t	f	f	\N			2081	\N
262	Customer	F	Hospitality		HCR	t	f	f	\N			2239	\N
263	Laboratory Officer	F	Healthcare and Health Promotion		HDI	t	f	f	\N			608	\N
264	Low advisor	F	Justice		HDI	t	f	f	\N			2023	\N
265	Excel society	F	Healthcare and Health Promotion		Health care aide	t	f	f	\N			2198	\N
266	Accountant officer	F	Education		High School EAR Church	t	f	f	\N			1940	\N
267	Front office Manager	F	Hospitality		Hill View Hotel & Apartment	t	f	f	\N			165	\N
268	Nursing	F	Healthcare and Health Promotion		Hopital Croix Du Sud	t	f	f	\N			158	\N
269	Customer Care	F	Healthcare and Health Promotion		Horebu Medical Clinic	t	f	f	\N			1895	\N
270	Nyamagabe Station Manager	F	Business		Horizon Ltd	t	f	f	\N			28	\N
271	Nurse Assistant	F	Healthcare and Health Promotion		Hospital Canada	t	f	f	\N			2423	\N
272	Receptionist	F	Hospitality		Hostel Kigali	t	f	f	\N			1985	\N
273	Maintenance	F	Technology		Hot Point	t	f	f	\N			156	\N
274	Housekeper	F	Hospitality		Housekeper	t	f	f	\N			722	\N
275	Talent Development Associate	F	Education		Human Ressource	t	f	f	\N			2242	\N
276	Data Cleck	F	Technology		Ignite Solar Power	t	f	f	\N			150	\N
277	Direct Sales officer (Retail Banking Department	F	Business		IM@Bank	t	f	f	\N			44	\N
278	IT officer	F	Technology		Imaranyundo Secondary School	t	f	f	\N			2071	\N
279	Accountant officer	F	Accounting		IMBARAGA	t	f	f	\N			2379	\N
280	Environment/Associate Engineer	F	Environment		Infosys Ltd	t	f	f	\N			1986	\N
281	Finance Officer	F	Education		Inkomoko	t	f	f	\N			1988	\N
282	Program Associate	F	Education		Institute of International Education	t	f	f	\N			2343	\N
283	Operation Manager	F	AAC Blocks		Integrated Infrastructures Co.Ltd	t	f	f	\N			2219	\N
284	Finance Assistant	F	Finamce		Intore Learning Center	t	f	f	\N			2223	\N
285	Investigator Officer	F	Security		Investigator	t	f	f	\N			601	\N
286	Saler officer	F	Business		Irembo Ltd	t	f	f	\N			2061	\N
287	Security Guide	F	Business		Irembo Service	t	f	f	\N			783	\N
288	IT Assistant	F	Security		ISCO Security	t	f	f	\N			2251	\N
289	Security officer	F	Security		ISCO security	t	f	f	\N			1584	\N
290	IT officer	F	Technology		Ishyinga Campany	t	f	f	\N			1498	\N
291	Community Manager & Data protection officer	F	Tecnhology		IT outsourcing Company	t	f	f	\N			1503	\N
292	Portfolio and management reporting officer	F	Business		Jali Finance	t	f	f	\N			2193	\N
293	Cashier	F	Business		Jibu - Huye	t	f	f	\N			1667	\N
294	Recruitment Assistant	F	Education		Job In Rwanda	t	f	f	\N			768	\N
295	Sales and Marketing Executive	F	Management		Jumeirah at Saadiyat Resort	t	f	f	\N			758	\N
445	Army	F	Security		Rwanda Defence Forces	t	f	f	\N			55	\N
296	Health Officer	F	Managemet		Kamonyi District	t	f	f	\N			2410	\N
297	procurement MANAGER	F	Business		Kapoa	t	f	f	\N			2374	\N
298	Waiter	F	Hospitality		Karibu Restraurant	t	f	f	\N			167	\N
299	Nurse	F	Healthcare and Health Promotion		Karongi Health Center	t	f	f	\N			2321	\N
300	Marketing	F	Business		Kasha	t	f	f	\N			2141	\N
301	Cashier	F	Business		Kawunga Minimex Depot Supplier	t	f	f	\N			2457	\N
302	Cashier	F	Hospitality		Kay Wedding Ltd	t	f	f	\N			759	\N
303	Cashier	F	Banking		KBC Bank	t	f	f	\N			32	\N
304	Lawyer	F	Education		Kefa project	t	f	f	\N			62	\N
305	Customer care	F	Healthcare and Health Promotion		Kibogora Hospital	t	f	f	\N			1912	\N
306	Property Administrator	F	Construction		Kigali Heights Development Company	t	f	f	\N			2269	\N
307	IT Teacher	F	Education		KIGARAMA TTS	t	f	f	\N			1958	\N
308	Waiter	F	Hospitality		Kimironko Cake House	t	f	f	\N			53	\N
309	Customer Care	F	Healthcare and Health Promotion		King faisal	t	f	f	\N			14	\N
310	Nurse	F	Healthcare and Health Promotion		King Faisal	t	f	f	\N			614	\N
311	House Keeping Supervisor	F	Hospitality		Kingfish Hotel	t	f	f	\N			1570	\N
312	Nurse	F	Healthcare and Health Promotion		Kirehe Hospital	t	f	f	\N			1546	\N
313	Technician in tilapia fish incubation	F	Aquaculture		Kivu choice	t	f	f	\N			2249	\N
314	Fish-Production officer	F	Business		Kivu Choice	t	f	f	\N			1557	\N
315	Selling Officer	F	Business		Kivu Choice	t	f	f	\N			27	\N
316	Chief Finance Officer	F	Business		Kivu Choice and Victory Farms Family	t	f	f	\N			114	\N
317	Procurement Officer Assistant	F	Business		Kivu Choice LTD	t	f	f	\N			706	\N
318	Business	F	IT		Kivu Choice LTD	t	f	f	\N			1508	\N
319	Operations Manager	F	Software Engineer		KORA Coaching Ltd, IHAHA Technologies Ltd	t	f	f	\N			1783	\N
320	Sushi Chef	F	Hospitality		Kozo Kigali	t	f	f	\N			1587	\N
321	Waiter	F	Hospitality		Kozo Kigali	t	f	f	\N			2088	\N
322	Trek Resident Leader	F	Business		Kurumbuka Leadership Solutions	t	f	f	\N			1970	\N
323	Waiter	F	Healthcare and Health Promotion		La Medicale Clinic	t	f	f	\N			2372	\N
324	Cashier	F	Business		Lamane Supermarket	t	f	f	\N			1681	\N
325	Cashier	F	Business		Lamane Supermarket	t	f	f	\N			750	\N
326	Cleaner	F	casal work		Lapallise hotel in	t	f	f	\N			2203	\N
327	Senior Accountant	F	Business		Leankeys Consultancy CPA Ltd	t	f	f	\N			48	\N
328	Laboratory Officer	F	Healthcare and Health Promotion		Legacy Clinic Hospitaly	t	f	f	\N			1710	\N
329	Office Attendant	F	Finance		Liedekerke	t	f	f	\N			2225	\N
330	Self Manager	F	Business		Liquer Small Bussiness	t	f	f	\N			122	\N
331	Cashier	F	Business		Liquid Wine Store Best Beginning	t	f	f	\N			703	\N
332	IT Data Analysis	F	Technology		Liquidnet New York	t	f	f	\N			125	\N
333	Finance Admin	F	Finamce		Look Ahead Care and Support	t	f	f	\N			2324	\N
334	Sales Manager	F	Business		M.T.RIC SUPPLIER LTD	t	f	f	\N			2456	\N
335	Education Officer/ Maison shalom international	F	Technology		Maison shalom international	t	f	f	\N			774	\N
336	Waiter	F	Hospitaliy		Malato Bar and Restaurant	t	f	f	\N			1504	\N
337	Store Keeper	F	Managemet		Mamba Sector	t	f	f	\N			2025	\N
338	Business operations assistant	F	Business		Mango 4G Internet	t	f	f	\N			2101	\N
339	Data Entry Cleck	F	Hospitality		Mango Internet Ltd	t	f	f	\N			1802	\N
340	Customer care	F	Telecommunication		Mango Internet Ltd	t	f	f	\N			2430	\N
341	Social Media Consultancy	F	Business		Maravilla Kivu Eco Resort	t	f	f	\N			2483	\N
342	Customer care	F	Hospitality		Marriot Hotel	t	f	f	\N			1823	\N
343	Food and beverage expert	F	Hospitality		Marriot Hotel	t	f	f	\N			2449	\N
344	Events service Expert	F	Hospitality		Marriott Hotel Kigali	t	f	f	\N			99	\N
345	Finance voyager	F	Hospitality		Marriott international (Kigali Marriott)	t	f	f	\N			1967	\N
346	Electrical engineering	F	Construction		Mass Design Group	t	f	f	\N			587	\N
347	Safety Officer	F	Construction		Mass Design Group	t	f	f	\N			1517	\N
348	Customer care	F	Business		Mc Donald Fast Food	t	f	f	\N			2295	\N
349	Cashier	F	Hospitality		Mid Land Hotel	t	f	f	\N			711	\N
350	Shop Attendnt	F	Business		Milimani Enterprise Ltd	t	f	f	\N			154	\N
351	Land officer	F	Managemet		MINADEF Project	t	f	f	\N			116	\N
352	Accountant officer	F	Business		Montana Motel	t	f	f	\N			2526	\N
353	Waiter	F	Hospitality		Motel Gabiro Milital	t	f	f	\N			1949	\N
354	Sales and marketing officer	F	Business		Mount meru soyco	t	f	f	\N			2079	\N
355	Téléphone Opérator	F	Hospitality		Movenpick Hotel at Dubai	t	f	f	\N			2365	\N
356	Waiter	F	Hospitality		Movenpick Hotel at Dubai	t	f	f	\N			2472	\N
357	Customer care	F	Communication		MTN	t	f	f	\N			2471	\N
358	Call center Officer	F	Business		MTN Call Center	t	f	f	\N			1551	\N
359	Head of Coffee	F	Hospitality		Mukatti na Butta coffee shop	t	f	f	\N			2054	\N
360	Customer Care	F	Business		Musanze Great Hotel	t	f	f	\N			2189	\N
361	Land Infrastructure and community settlement	F	Managemet		Musanze Sector	t	f	f	\N			590	\N
362	Waiter	F	Hospitality		Mystol Hotel	t	f	f	\N			2161	\N
363	Manager Assistant	F	Hospitality		Mytos Hotel	t	f	f	\N			1863	\N
364	Restua	F	Hospitality		Mytos Hotel	t	f	f	\N			805	\N
365	Store Keeper Officer	F	Construction		NDOSA Campany	t	f	f	\N			139	\N
366	Receptionist	F	Hospitality		Nest Kim	t	f	f	\N			1678	\N
367	Supervisor	F	Agribusiness		NetaFim Rwanda	t	f	f	\N			2354	\N
368	Customer care	F	Managemet		Ngoma District	t	f	f	\N			2118	\N
369	Cultivator	F	Agribusiness		Local government	t	f	f	\N			2412	\N
370	Cultivator	F	Agribusiness		Local government	t	f	f	\N			2080	\N
371	Nurse Assistant	F	Healthcare and Health Promotion		Nurse assistant	t	f	f	\N			2317	\N
372	Marketing officer	F	Business		Nutri toto Campany	t	f	f	\N			1717	\N
373	Store Officer	F	Business		Nyabisindu Milk Zone Head	t	f	f	\N			140	\N
374	Statistic Officer	F	Staticstics		Nyamasheke District	t	f	f	\N			1812	\N
375	Laboratory Officer	F	Healthcare and Health Promotion		Nyanza Hospital District	t	f	f	\N			2107	\N
376	Customer Care	F	Business		Nyaruguru Coffee Shop	t	f	f	\N			652	\N
377	Finance Officer	F	Managemet		Nyaruguru District	t	f	f	\N			1756	\N
378	Finance Officer	F	Education		Obama Language Training	t	f	f	\N			2312	\N
379	Field Integration Supervisor	F	Agribusiness		One acre fund	t	f	f	\N			2328	\N
380	Farmer Credit Recovery Operation Associate	F	Agribusiness		One Acre Fund Rwanda	t	f	f	\N			2261	\N
381	Pshop Manager/Nyamagabe	F	Agribusiness		One Acre Fund Rwanda	t	f	f	\N			2283	\N
382	Data officer	F	Education		One Acre Fund Rwanda	t	f	f	\N			2201	\N
383	Journalist	F	Communication		One Acree Fund	t	f	f	\N			684	\N
384	Waiter	F	Hospitality		Onomo Hotel	t	f	f	\N			2419	\N
385	Managing Director	F	Business		OX Rwanda Ltd	t	f	f	\N			2409	\N
386	Stock Officer	F	Healthcare and Health Promotion		PAM	t	f	f	\N			2414	\N
387	Cashier	F	Business		PAPYRUS	t	f	f	\N			1476	\N
388	Guest Service Agent	F	Hospitality		Park Inn by Radisson Kigali	t	f	f	\N			2248	\N
389	Data Cleck	F	Technology		Pascal Technology	t	f	f	\N			1712	\N
390	Cashier	F	Business		Patroleum Station Byimana	t	f	f	\N			700	\N
391	Complex FS/QA Supervisor	F	Agribusiness		Perdue Farms	t	f	f	\N			2274	\N
392	Data Entry Cleck	F	Technology		Petrocom	t	f	f	\N			1572	\N
393	Cashier	F	Hospitality		Pharmacy Cocoride	t	f	f	\N			2167	\N
394	Cashier	F	Healthcare and Health Promotion		Pharmacy Nobillis	t	f	f	\N			1834	\N
395	Photographer	F	Business		Photographer Envision  Ltd	t	f	f	\N			104	\N
396	Executive Assistant	F	Agribusiness		Poc Farmer	t	f	f	\N			752	\N
397	Nurse	F	Healthcare and Health Promotion		Police Hospital	t	f	f	\N			1924	\N
398	Marketing officer	F	Banking		Popular Bank of Rwanda	t	f	f	\N			1708	\N
399	IT Manager	F	Technology		Price Water House Coopers	t	f	f	\N			2455	\N
400	Cashier	F	Business		Pride Farm	t	f	f	\N			2026	\N
401	Customer Care	F	Business		Pride Farm	t	f	f	\N			1845	\N
402	Sales Manager	F	Business		Pride Farm	t	f	f	\N			2019	\N
403	Policy Analyst | Office of the Prime Minister	F	Managemet		Prime Minister of Rwanda	t	f	f	\N			1669	\N
404	NCBA Bank	F	Business		Professional internship at Water Access Rwanda	t	f	f	\N			93	\N
405	Legal Officer	F	Managemet		Project Of Legal Officer	t	f	f	\N			1624	\N
406	Customer Care	F	Hospitality		Quatar Hotel	t	f	f	\N			1964	\N
407	Customer Care	F	Hospitality		Quatar Hotel	t	f	f	\N			2313	\N
408	Receptionist	F	Business		Radiant Insurance	t	f	f	\N			1991	\N
409	E-BUSINESS OFFICER	F	Business		Bank of Africa	f	f	f	\N			1707	\N
410	Store Manager	F	Hospitality		Rainbow  Motel	t	f	f	\N			137	\N
411	Intern(Nurse)	F	Healthcare and Health Promotion		RBC	t	f	f	\N			2339	\N
412	Army-RDF	F	Security		RDF	t	f	f	\N			101	\N
413	Army	F	Security		RDF Army	t	f	f	\N			2051	\N
414	Electrical Engineering	F	Energy		Real Construction	t	f	f	\N			1581	\N
415	MD Assistant	F	Business		Real Contractors Ltd	t	f	f	\N			686	\N
416	Real Estate Broker	F	Business		Real Estate	t	f	f	\N			22	\N
417	Waiter	F	Hospitality		Redison Blue Hotel	t	f	f	\N			20	\N
418	SPM Officer	F	Environment		REDO	t	f	f	\N			2268	\N
419	Administrator	F	Construction		Remote Group	t	f	f	\N			2495	\N
420	Site Logistic Coordinator	F	Construction		Remote Group	t	f	f	\N			612	\N
421	Site Logistic Coordinator	F	Management		Remote Group	t	f	f	\N			1961	\N
422	Site Agent Officer	F	Construction		Remote Group LTD	t	f	f	\N			65	\N
423	Receptionist	F	Business		Remote LTD	t	f	f	\N			2433	\N
424	Product Manager	F	Energy		Renewable Energy	t	f	f	\N			2033	\N
425	Receptionist	F	Managemet		RIB	t	f	f	\N			1606	\N
426	Accountant officer	F	Business		River trading limited	t	f	f	\N			1730	\N
427	Production Site Manager	F	Business		RP Corporate Ltd	t	f	f	\N			2073	\N
428	Verficator	F	Healthcare and Health Promotion		RSSB	t	f	f	\N			1514	\N
429	Data officer	F	Managemet		RSSB	t	f	f	\N			2233	\N
430	Sharoir	F	Business		RTTC	t	f	f	\N			1652	\N
431	Project Assistant	F	Agribusiness		RTV( Raising the Village)	t	f	f	\N			2461	\N
432	Teacher of Mathematic	F	Education		Rubavu Primary School	t	f	f	\N			164	\N
433	Waiter	F	Hospitality		Rubis Supermarket	t	f	f	\N			1887	\N
434	Teacher	F	Education		Rugendo Secondary School	t	f	f	\N			1918	\N
435	Customer care	F	Healthcare and Health Promotion		Rulindo Hospital	t	f	f	\N			695	\N
436	Waiter	F	Hospitality		Rutsiro Hotel	t	f	f	\N			1538	\N
437	Supervisor	F	Agribusiness		Rwamagana Agriculture Business	t	f	f	\N			1793	\N
438	Audit Officer	F	Business		Rwanda Audit	t	f	f	\N			1767	\N
439	Nurse	F	Healthcare and Health Promotion		Rwanda Biomedical	t	f	f	\N			2028	\N
440	Nurse	F	Healthcare and Health Promotion		Rwanda Biomedical	t	f	f	\N			1567	\N
441	Editing Manager	F	Communication		Rwanda Broadcasting Agency	t	f	f	\N			2169	\N
442	Journalist	F	Communication		Rwanda Broadcasting Agency	t	f	f	\N			1451	\N
443	Army	F	Security		Rwanda Defence Force	t	f	f	\N			2297	\N
446	Army	F	Security		Rwanda Defence Forces	t	f	f	\N			38	\N
447	Army	F	Security		Rwanda Defence Forces	t	f	f	\N			2173	\N
448	Army	F	Security		Rwanda Defence Forces	t	f	f	\N			1797	\N
449	Army	F	Security		Rwanda Defence Forces	t	f	f	\N			2267	\N
450	Operator Manager	F	Hospitality		Rwanda events	t	f	f	\N			1714	\N
451	Tractor Operator	F	Education		Rwanda Institute For Conservation Agriculture (RICA)	t	f	f	\N			2024	\N
452	Procumenent and Logistic	F	Healthcare and Health Promotion		Rwanda interfaith Council on Health	t	f	f	\N			688	\N
453	Data officer	F	Managemet		Rwanda Investigation Bureau	t	f	f	\N			1921	\N
454	RIB Officer	F	Managemet		Rwanda Investigation Bureau	t	f	f	\N			1801	\N
455	Secretariat	F	Managemet		Rwanda Investigation Bureau	t	f	f	\N			1914	\N
456	RIB Offcier	F	Security		Rwanda Investigation Bureau	t	f	f	\N			1689	\N
457	Nurse	F	Healthcare and Health Promotion		Rwanda Military Hospital	t	f	f	\N			2326	\N
458	Media Analyst	F	Education		Rwanda Nation Police	t	f	f	\N			2158	\N
459	Policy men	F	Managemet		Rwanda Nation Police	t	f	f	\N			2304	\N
460	Policy men	F	Managemet		Rwanda Nation Police	t	f	f	\N			1979	\N
461	Police	F	Security		Rwanda Nation Police	t	f	f	\N			2065	\N
462	Policy	F	Security		Rwanda Nation Police	t	f	f	\N			1868	\N
463	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			1955	\N
464	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			1585	\N
465	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			63	\N
466	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			2301	\N
467	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			2003	\N
468	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			1542	\N
469	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			2128	\N
470	Policy men	F	Security		Rwanda Nation Police	t	f	f	\N			1787	\N
471	Policemen	F	Security		Rwanda Police	t	f	f	\N			1827	\N
472	Policiwomen	F	Security		Rwanda Police	t	f	f	\N			1953	\N
473	Communication Officer	F	Administration Officer		Rwandair	t	f	f	\N			1804	\N
474	Flyer Service	F	Hospitality		Rwandair	t	f	f	\N			2014	\N
475	Customer care	F	Business		Rwandair	t	f	f	\N			1521	\N
476	Customer Care	F	Hospitality		Rwandair	t	f	f	\N			1531	\N
477	Manager	F	Business		Salama Jus Ltd -	t	f	f	\N			2439	\N
478	Quality inspection	F	Business		Salcomp	t	f	f	\N			160	\N
479	Quality inspection	F	Business		Salcomp	t	f	f	\N			159	\N
480	Journalist	F	Communication		Salus Radio	t	f	f	\N			719	\N
481	Journalist	F	Communication		Salus Radio	t	f	f	\N			615	\N
482	Logistic officer	F	Business		Sanlam	t	f	f	\N			18	\N
483	Waiter	F	Business		Sawa City Supermarket-Nyarutarama	t	f	f	\N			91	\N
484	Rwandaequip	F	Education		Schools,Supervisor	t	f	f	\N			1541	\N
485	Sales agent	F	Business		See Far Housing	t	f	f	\N			1884	\N
486	Quantity Surveyor	F	Construction		See Far Housing	t	f	f	\N			157	\N
487	Driver	F	Hospitality		See Far Housing	t	f	f	\N			2159	\N
488	Sales Assistant	F	Business		SEE FAR HOUSING LTD	t	f	f	\N			2126	\N
489	Manager Business	F	Business		Selling Home Materiels	t	f	f	\N			1938	\N
490	Cashier	F	Business		Selling Materiel Design	t	f	f	\N			1747	\N
491	Administrative Assistant	F	Hospitality		Senior Banking Officer	t	f	f	\N			1599	\N
492	Hair Cut	F	business		Shaving Salon	t	f	f	\N			1523	\N
493	Senior technician	F	Electricite		Shema Power Lake Kivu(SPLK)	t	f	f	\N			2052	\N
494	Data Analysis	F	Business		Shine Cleaner Ltd	t	f	f	\N			683	\N
495	Reservation&Marketing Officer	F	Hospitality		Shipment Campany	t	f	f	\N			1594	\N
496	Self Manager	F	Business		Shoes Shop- Down Tawn	t	f	f	\N			1589	\N
497	Cashier	F	Business		Shop Clother	t	f	f	\N			1774	\N
498	Receptionist	F	Business		Sonia Mugabo Fashion Designer	t	f	f	\N			616	\N
499	Editing Journaliste	F	Communication		Southern Province Headquater	t	f	f	\N			2150	\N
500	Manager	F	Hospitality		Soy Restaurant	t	f	f	\N			2046	\N
501	Accountant officer	F	Business		SP Head Quarter	t	f	f	\N			1846	\N
502	Trainer Officer	F	Education		Spark Microgrants	t	f	f	\N			144	\N
503	Software Engineer	F	Technology		Spiderbit LTD	t	f	f	\N			1942	\N
504	Selling Officer	F	Technology		Square Technology Limited	t	f	f	\N			738	\N
505	Mentor(Animatrice)	F	Education		St Marie	t	f	f	\N			2521	\N
506	Lead Supervisor and Sales Adviser	F	Communication		Startup in Seattle	t	f	f	\N			2093	\N
507	Logistic officer	F	Construction		Stell-Rwanda	t	f	f	\N			29	\N
508	Logistic officer	F	Construction		Stell-Rwanda	t	f	f	\N			1758	\N
509	Stock management	F	Business		Stock management	t	f	f	\N			1809	\N
510	Safety Officer	F	Construction		Suma Construction LTD	t	f	f	\N			2086	\N
511	Website Development	F	Technology		SunShine Ltd	t	f	f	\N			1856	\N
512	Waiter	F	Hospitality		Supermarket at Gisimenti	t	f	f	\N			2013	\N
513	Waiter	F	Hospitality		Supermarket Kimironko	t	f	f	\N			1892	\N
514	Sales Agent	F	Business		SWAVU Ltd/ sales Agent	t	f	f	\N			2284	\N
515	Librarian Assistant Humanities and Social Science	F	Education		Swiztland	t	f	f	\N			602	\N
516	Receptionist	F	Hospitality		Syneduc	t	f	f	\N			769	\N
517	Project Manager	F	Business		Tarama Rwanda Ltd	t	f	f	\N			1722	\N
518	Technical Support Engineer	F	Technology		Tek expert Rwanda Ltd	t	f	f	\N			2157	\N
519	Technology Support Engineer	F	Technology		Tek expert Rwanda Ltd	t	f	f	\N			1579	\N
520	Consultant	F	Agribusiness		The Daugherty Water for food Global Institute	t	f	f	\N			2278	\N
521	Waiter	F	Hospitality		The Fork	t	f	f	\N			702	\N
522	Receptionist	F	Hospitality		The Keza Hotel -Kibagabaga	t	f	f	\N			627	\N
523	Manager Assistant	F	Hospitality		Thousand Hills Africa	t	f	f	\N			1696	\N
524	Operations	F	Hospitality		Thousand Hills Africa	t	f	f	\N			2130	\N
525	Power Systems	F	Enginer		Totes Scottish Power	t	f	f	\N			2493	\N
526	Tour guide	F	Hospitality		Tour Campany Ltd	t	f	f	\N			26	\N
527	Customer Support Specialist	F	Business		Toyota Tanzania Ltd	t	f	f	\N			1486	\N
528	Teacher Assistant	F	Education		TTC Bicumbi	t	f	f	\N			2114	\N
529	Site Manager	F	Agribusiness		Tubura Campany	t	f	f	\N			1867	\N
530	Supervisor	F	Agribusiness		Tubura Campany	t	f	f	\N			1917	\N
531	Presentor	F	Communication		TV 10	t	f	f	\N			1859	\N
532	Driver	F	Industry		Uber Campany	t	f	f	\N			1792	\N
533	Social Worker	F	Education		Under Hils Umbrella	t	f	f	\N			161	\N
534	Photographer	F	Art		Uniqwe studio	t	f	f	\N			1686	\N
535	Manager	F	Business		United Arabie Emirate	t	f	f	\N			112	\N
536	Research Officer	F	Healthcare and Health Promotion		University of Rwanda -Holding Group	t	f	f	\N			2022	\N
537	Social Worker	F	Healthcare and Health Promotion		University of Rwanda -Holding Group	t	f	f	\N			2280	\N
538	Coacher	F	Education		USAID Gikundiro/Gisagara	t	f	f	\N			735	\N
539	Waiter	F	Hospitality		UTC restaurant	t	f	f	\N			2230	\N
540	Logistic officer	F	Construction		VASCO Constuction campany	t	f	f	\N			2528	\N
541	Actuarial Associate	F	Business		Venerable Insurance Company	t	f	f	\N			715	\N
542	Data Analysis	F	Technology		VIDA	t	f	f	\N			2124	\N
543	Geospatial data scientist	F	Technology		VIDA	t	f	f	\N			1452	\N
544	Healthcare officer	F	Healthcare and Health Promotion		Virginia Mason Hospital and Capalitity health care	t	f	f	\N			2418	\N
545	IT officer	F	Technology		WASAC	t	f	f	\N			585	\N
546	Store officer	F	Business		Water Company	t	f	f	\N			2362	\N
547	Self Manager	F	Business		Wedding Boutique	t	f	f	\N			2382	\N
548	Business in Tech consultant	F	Technology		Wells Fargo	t	f	f	\N			2350	\N
549	Data officer	F	Business		Wells Fargo Bank/Data Analysis	t	f	f	\N			724	\N
550	Supervisor	F	Business		Wholrfoods Market	t	f	f	\N			2397	\N
551	Coding Program Coordinator	F	IT		Women in Africa	t	f	f	\N			2102	\N
552	Store Invetor Officer	F	Healthcare and Health Promotion		World Food Rwanda	t	f	f	\N			743	\N
553	Logistic officer	F	Business		World Vision	t	f	f	\N			1798	\N
554	Business Development officer	F	Business		Yego Moto Campany LTD	t	f	f	\N			2522	\N
555	Youth Worker	F	Healthcare and Health Promotion		YMCA Montreal	t	f	f	\N			1720	\N
556	Food processing	F	Agribusiness		Zamura feeds	t	f	f	\N			1719	\N
557	Management Trainee	F	Agribusiness		Zamura Feeds	t	f	f	\N			106	\N
558	General Manager	F	Hospitality		Zebra Hotel	t	f	f	\N			2440	\N
559	Waiter	F	Hospitality		Zebra Hotel	t	f	f	\N			2132	\N
560	Executive Assistant	F	Local Government		Zoniheza	t	f	f	\N			1525	\N
561	IT support technician	P	technology		Abilene Christian university	f	f	f	\N			1733	\N
562	Students plus volunteering at AIESEC at kigali as a marketing director.	P	Education		AEISEC	f	f	f	\N			1558	\N
563	Sewing Assistant	P	Art		Agahozo-Shalom Youth Village	f	f	f	\N			58	\N
564	Canteen Waiter	P	Business		Agahozo-Shalom Youth Village	f	f	f	\N			2035	\N
565	Basketball Player	P	Sport		APR	f	f	f	\N			1816	\N
566	Casual Worker	P	Education		Agahozo-Shalom Youth Village	f	f	f	\N			69	\N
567	IT Trainer	P	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2012	\N
568	Threatre Coacher	P	Education		Agahozo-Shalom Youth Village	f	f	f	\N			2036	\N
569	Casual worker	P	Hospitality		Agahozo-Shalom Youth Village	f	f	f	\N			669	\N
570	Casual worker	P	Hospitality		Agahozo-Shalom Youth Village	f	f	f	\N			1806	\N
571	Casual worker	P	Hospitality		Agahozo-Shalom Youth Village	f	f	f	\N			2533	\N
572	IT Pyton Trainer	P	Technology		Agahozo-Shalom Youth Village	f	f	f	\N			1530	\N
573	Farmer	P	Education		ASYV	f	f	f	\N			1595	\N
574	Farmer	P	Education		ASYV	f	f	f	\N			2142	\N
575	Waiter	P	Hospitality		Envision Rwanda	f	f	f	\N			105	\N
576	Self- Manager	P	Cashier		BRAC Rwanda	f	f	f	\N			1897	\N
577	Cashier	P	Business		Clothes Shop	f	f	f	\N			709	\N
578	Building House	P	Construction		Construction	f	f	f	\N			1963	\N
579	Painting	P	Construction		Convention Centre	f	f	f	\N			1828	\N
580	Baristae	P	Business		Customer care services-Coffee Sonatube	f	f	f	\N			1492	\N
581	General Doctor	P	Healthcare and Health Promotion		DMC Hospital	f	f	f	\N			2043	\N
582	Driver	P	Business		Driver Campany	f	f	f	\N			2215	\N
583	Photographer	P	Art		Envision Rwanda	f	f	f	\N			2066	\N
584	Photographer	P	Art		Envision Rwanda	f	f	f	\N			2241	\N
585	Cashier/Waiter	P	Business		Envision Rwanda	f	f	f	\N			2438	\N
586	Food and Beverage	P	Hospitality		Four points by Sheraton kigali	t	f	f	\N			2531	\N
587	Teacher Intern	P	Education		G.S Murunda	t	f	f	\N			1545	\N
588	Volunter	P	Managemet		Gasabo District	t	f	f	\N			1901	\N
589	Supervisor-Road	P	Business		GhettoLtd	t	f	f	\N			1829	\N
590	Waiter	P	Hospitality		Gorilla Hotel	t	f	f	\N			2368	\N
591	Teacher	P	Education		GS kabitovu- Rutsiro	t	f	f	\N			2191	\N
592	Customer Care	P	Hospitality		Health Center	t	f	f	\N			2168	\N
593	Human Ressource Assistant	P	Business		Human Ressource Assistant	t	f	f	\N			94	\N
594	Teacher	P	Education		Huye Nursery	t	f	f	\N			96	\N
595	Waiter	P	Business		Jill and Bar Restaurant	t	f	f	\N			15	\N
596	Dancer	P	Business		Dance Modern	f	f	f	\N			2069	\N
597	Teacher Intern	P	Education		Liquidnet Family High School@asyv	t	f	f	\N			2240	\N
598	Dancing	P	Business		Intayoberanya Traditional	t	f	f	\N			2309	\N
599	Tek Experts	P	Technology		Microsoft Technical Support Engineer	t	f	f	\N			2245	\N
600	Call Operator	P	Business		MTN	t	f	f	\N			1562	\N
601	Selling MTN Airtime at Muhanga	P	Business		MTN	t	f	f	\N			138	\N
602	Agent	P	Business		MTN Agent	t	f	f	\N			753	\N
603	Waiter	P	Hospitality		Mytos Hotel	t	f	f	\N			2458	\N
604	Teacher	P	Education		Ngoma District	t	f	f	\N			1598	\N
605	Dancing	P	Dancing		Local government	t	f	f	\N			1721	\N
606	Casual Worker	P	Education		Local government	t	f	f	\N			1765	\N
607	Cashier	P	Hospitality		Nyabugogo Papeterie	t	f	f	\N			1578	\N
608	Commissionaire	P	Business		RAA	t	f	f	\N			1699	\N
609	Laboraty	P	Healthcare and Health Promotion		RBC	t	f	f	\N			1482	\N
610	Customer Care	P	Business		Restaurant	t	f	f	\N			659	\N
611	Waiter	P	Hospitality		Restaurant	t	f	f	\N			712	\N
612	Waiter	P	Hospitality		Restaurant Gisimenti	t	f	f	\N			2367	\N
613	Photography/Cameramen	P	Communication		Rwanda Broadcasting Agency	t	f	f	\N			2520	\N
614	Singer-Women	P	Business		Self - Musician	t	f	f	\N			1677	\N
615	Driver/UBER	P	Business		Self-employed	t	f	f	\N			1540	\N
616	Art- Music	P	Music		Self-employed	t	f	f	\N			100	\N
617	Self-Employed	P	Business		Selling Airtime	t	f	f	\N			2089	\N
618	Self-Manager	P	Business		Selling Banane in the Market (Gatore)	t	f	f	\N			592	\N
619	Marketing officer	P	Business		Selling ONGO Produit	t	f	f	\N			2060	\N
620	Cashier	P	Business		Selling Telephone Mobile T2000	t	f	f	\N			1832	\N
621	Supervisor of Waiter	P	Hospitality		Serena Hotel	t	f	f	\N			60	\N
622	Cashier	P	Business		Shop Clothes	t	f	f	\N			1566	\N
623	Cashier	P	Business		Small Boutique	t	f	f	\N			2399	\N
624	Technician	P	Technology		SP Station	t	f	f	\N			1582	\N
625	Tutoring Teacher	P	Education		Teaching	t	f	f	\N			2156	\N
626	Waiter	P	Hospitality		Tedga Center	t	f	f	\N			1490	\N
627	Design Art	P	Education		ASYV- Science center	f	f	f	\N			1509	\N
628	Marketing	P	Business		Tubura Campany	t	f	f	\N			1749	\N
629	Data  Entry	P	Education		Twiyubake, Gimbuka and Gikuriro (CRS-USAID)	t	f	f	\N			726	\N
630	Phtoto and Movie Editing	S	Business		Afrimage Photograph	f	f	f	\N			1706	\N
631	Selling Officer	S	Business		Agent Mobile Banking and Agent of Banking	f	f	f	\N			578	\N
632	RETAIR MANAGER	S	Agribusiness		Agriculture Business for Unit	f	f	f	\N			2510	\N
633	Manager	S	Agribusiness		Agriculture-Chia Seeds	f	f	f	\N			2475	\N
634	Her own business	S	Business		Clothers Shop	f	f	f	\N			1660	\N
635	Self-Manager	S	Business		Bar and Restaurant Karembure	f	f	f	\N			1904	\N
636	Self-Employed	S	Business		Benjamin Fashion Design	f	f	f	\N			2442	\N
637	Self Manager	S	Business		Body Lotion	f	f	f	\N			145	\N
638	Self-Manager	S	Business		Boutique	f	f	f	\N			1929	\N
639	Self-Manager	S	Business		Boutique	f	f	f	\N			1485	\N
640	Self-Manager	S	Business		Boutique Nyamata	f	f	f	\N			1580	\N
641	Self-Manager	S	Business		Boutique Shop	f	f	f	\N			23	\N
642	Selling Officer	S	Business		Boutique Shop	f	f	f	\N			2147	\N
643	Self-Employed	S	Business		Business- Clothes Shop	f	f	f	\N			1675	\N
644	Manager	S	Business		Business Hardware/Clothes Shop	f	f	f	\N			1560	\N
645	Self-Manager	S	Business		Business-Bumbogo	f	f	f	\N			2403	\N
646	Selling Officer	S	Business		Canteen Masizi	f	f	f	\N			1900	\N
647	Manager Herself	S	Business		Canteen Nyamata	f	f	f	\N			1960	\N
648	Manager	S	Business		Clarise spare parts	f	f	f	\N			1539	\N
649	Her own business	S	Business		Hardware - Huye	t	f	f	\N			794	\N
650	Self-Employed	S	Business		Clothers Shop	f	f	f	\N			2532	\N
651	Customer care	S	Business		Clothes Shop	f	f	f	\N			2078	\N
652	Self-Manager	S	Business		Clothes Shop	f	f	f	\N			2190	\N
653	Self-Manager	S	Business		Clothes Shop	f	f	f	\N			2505	\N
654	Manager	S	Construction		Construction Campany	f	f	f	\N			1751	\N
655	Self-Employed	S	Business		Constuction Campany	f	f	f	\N			1873	\N
656	Owner	S	Hospitality		Cyber	f	f	f	\N			98	\N
657	Customer care	S	Business		Decoration Company Ltd	f	f	f	\N			723	\N
658	Manager	S	Business		Edebn supply Ltd	f	f	f	\N			1894	\N
659	Self Manager	S	Business		Ghetto Ltd	t	f	f	\N			2045	\N
660	Director  Manager	S	Hospitality		Go-Discovery Africa	t	f	f	\N			2277	\N
661	Producer	S	Art		H5T Studio	t	f	f	\N			1759	\N
662	Hair Salom Manager	S	Business		Hair Salon at Remera	t	f	f	\N			33	\N
663	Self-Manager	S	Business		Hardware at Nyanza	t	f	f	\N			2400	\N
664	Self-Manager	S	Business		Hardware LMTD	t	f	f	\N			1983	\N
665	Self-Employed	S	Business		Her ow Business	t	f	f	\N			155	\N
666	Self-Manager	S	Business		Her ow Business	t	f	f	\N			1625	\N
667	Shop	S	Business		Her ow Business	t	f	f	\N			1518	\N
668	Self-Manager	S	Business		Bar and Restaurant	f	f	f	\N			30	\N
669	Self-Manager	S	Business		Irembo Ltd	t	f	f	\N			1575	\N
670	Manager	S	Business		Keza Shoes Shop	t	f	f	\N			2098	\N
671	Carrier Relations Manager	S	Consultant		Kigali Business Lab and Consulting Firm	t	f	f	\N			1977	\N
672	Businesswomen	S	Business		Kigali-City Market	t	f	f	\N			1640	\N
673	Self-Manager	S	Technology		Educate for IT	f	f	f	\N			25	\N
674	Customer care	S	Business		Livecleanrwanda Ltd	t	f	f	\N			2476	\N
675	Protocal	S	Business		Milk Zone	t	f	f	\N			2220	\N
676	Manager	S	Business		Moto Piece de Recharge	t	f	f	\N			2404	\N
677	Self Manager	S	Business		MTN Agent	t	f	f	\N			2305	\N
678	Self-Employed	S	Business		Musician	t	f	f	\N			1547	\N
679	Photographer and Video Edite	S	Business		Photograph Mica Ltd	t	f	f	\N			2002	\N
680	Photography Art	S	IT		Photography	t	f	f	\N			2484	\N
681	Musician	S	Business		Pianiste	t	f	f	\N			1495	\N
682	PHSA	S	Business		Premium west construction	t	f	f	\N			1945	\N
683	Self-Manager	S	Business		Production of quality cleaning accessories (F.N HYGIENE LTD	t	f	f	\N			2170	\N
684	Customer care	S	Business		Quicaillirie Nyamata	t	f	f	\N			2416	\N
685	DJ Berto	S	Business		Self-employed	t	f	f	\N			31	\N
686	Making Bread at Kinshansa	S	Business		Self-employed	t	f	f	\N			92	\N
687	Manager	S	Business		Self-employed	t	f	f	\N			2059	\N
688	Manager Sparks Moto	S	Business		Self-employed	t	f	f	\N			142	\N
689	Managing Director	S	Business		Self-employed	t	f	f	\N			2037	\N
690	Photography/Cameramen	S	Business		Self-employed	t	f	f	\N			763	\N
691	Self Manager	S	Business		Self-employed	t	f	f	\N			2226	\N
692	Self-Employed	S	Business		Self-employed	t	f	f	\N			591	\N
693	Self-Employed	S	Business		Self-employed	t	f	f	\N			733	\N
694	Self-Manager	S	Business		Self-employed	t	f	f	\N			2272	\N
695	Singer	S	Business		Self-employed	t	f	f	\N			2236	\N
696	Manager	S	Business		Selling Chicken	t	f	f	\N			2127	\N
697	Marketing	S	Business		Selling Clothers	t	f	f	\N			586	\N
698	Self-Employed	S	Business		Selling Clothes, Shoes	t	f	f	\N			2032	\N
699	Self-Employed	S	Business		Selling Mobile Phone	t	f	f	\N			2426	\N
700	Commissionaire	S	Business		Selling Sac and other clothes	t	f	f	\N			2153	\N
701	Cashier	S	Business		Selling Telephone	t	f	f	\N			2039	\N
702	Saler officer	S	Business		Selling Telephone Mobil- Remera	t	f	f	\N			2259	\N
703	Sewing Business	S	Hospitality		Sewing	t	f	f	\N			1919	\N
704	Sewing	S	Business		Sewing House	t	f	f	\N			1898	\N
705	Self-Manager	S	Business		Shop	t	f	f	\N			1650	\N
706	Waiter	S	Business		Shop at Kayonza Gare	t	f	f	\N			1479	\N
707	CEO	S	Business		Shop Clother Business	t	f	f	\N			1779	\N
708	Selling Officer	S	Business		Shop Clothers-Kimironko	t	f	f	\N			1994	\N
709	Self-Manager	S	Business		Small Boutique at Busanza	t	f	f	\N			1487	\N
710	Self-Employed	S	Body Lotion		Small Boutique at Kicukiro	t	f	f	\N			2165	\N
711	Rulindo Bar	S	Business		Small Business Bar	t	f	f	\N			1488	\N
712	Sales agent	S	Business		Small Supermarket Huye District	t	f	f	\N			1630	\N
713	Supermarket Manager	S	Business		Supermarket	t	f	f	\N			2194	\N
714	Cashier	S	Business		Supermarket Ruyenzi	t	f	f	\N			1513	\N
715	Supplier/ Businessman	S	Business		Supplier Business	t	f	f	\N			576	\N
716	Self-Manager	S	Agribusiness		Tea Agriculture	t	f	f	\N			1536	\N
717	Co-founder & Chief Operation Officer	S	Agribusiness		Verve Ag- Innovate Ltd	t	f	f	\N			2145	\N
718	Coordinator	S	Business		Yakfair	t	f	f	\N			2504	\N
719	Cashier	I	Hospitality		Chez Attoinet	f	f	f	\N			1568	\N
720	Teacher Assistant	I	Education		G.S Musanze	t	f	f	\N			11	\N
721	Hair Salom Manager	I	Hospitality		Local government	t	f	f	\N			2527	\N
722	Big Sister	I	Management		Local government	t	f	f	\N			2185	\N
723	Cashier	I	Management		Local government	t	f	f	\N			2271	\N
724	Cashier	I	Management		Local government	t	f	f	\N			2370	\N
725	IT Intern	I	Management		Local government	t	f	f	\N			2211	\N
726	IT Intern	I	Management		Local government	t	f	f	\N			1603	\N
727	IT Intern	I	Management		Local government	t	f	f	\N			1505	\N
728	LEAP Officer	I	Management		Local government	t	f	f	\N			1975	\N
729	Visitor Assistant Officer	I	Management		Local government	t	f	f	\N			721	\N
730	Recruitment Officer	I	Education		VATEL	t	f	f	\N			751	\N
\.


--
-- TOC entry 3414 (class 0 OID 0)
-- Dependencies: 249
-- Name: api_employment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_employment_id_seq', 730, true);


--
-- TOC entry 3261 (class 2606 OID 68738)
-- Name: api_employment api_employment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_employment
    ADD CONSTRAINT api_employment_pkey PRIMARY KEY (id);


--
-- TOC entry 3259 (class 1259 OID 68764)
-- Name: api_employment_alumn_id_c881ce1c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_employment_alumn_id_c881ce1c ON public.api_employment USING btree (alumn_id);


--
-- TOC entry 3262 (class 1259 OID 68765)
-- Name: api_employment_recorded_by_id_bc75eb10; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_employment_recorded_by_id_bc75eb10 ON public.api_employment USING btree (recorded_by_id);


--
-- TOC entry 3263 (class 2606 OID 68754)
-- Name: api_employment api_employment_alumn_id_c881ce1c_fk_api_kid_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_employment
    ADD CONSTRAINT api_employment_alumn_id_c881ce1c_fk_api_kid_id FOREIGN KEY (alumn_id) REFERENCES public.api_kid(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3264 (class 2606 OID 68759)
-- Name: api_employment api_employment_recorded_by_id_bc75eb10_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_employment
    ADD CONSTRAINT api_employment_recorded_by_id_bc75eb10_fk_api_user_id FOREIGN KEY (recorded_by_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-06-03 16:49:26

--
-- PostgreSQL database dump complete
--

