--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2025-06-04 16:46:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 254 (class 1259 OID 68746)
-- Name: api_furthereducation; Type: TABLE; Schema: public; Owner: postgres
--


DROP TABLE IF EXISTS public.api_furthereducation CASCADE;

CREATE TABLE public.api_furthereducation (
    id bigint NOT NULL,
    level character varying(3) NOT NULL,
    degree character varying(2500) NOT NULL,
    scholarship character varying(3) NOT NULL,
    scholarship_details character varying(2000) NOT NULL,
    status character varying(3) NOT NULL,
    alumn_id bigint NOT NULL,
    application_result character varying(1) NOT NULL,
    enrolled boolean NOT NULL,
    waitlisted boolean NOT NULL,
    college_id bigint NOT NULL,
    crc_support boolean NOT NULL
);


ALTER TABLE public.api_furthereducation OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 68745)
-- Name: api_furthereducation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_furthereducation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_furthereducation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3408 (class 0 OID 68746)
-- Dependencies: 254
-- Data for Name: api_furthereducation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_furthereducation (id, level, degree, scholarship, scholarship_details, status, alumn_id, application_result, enrolled, waitlisted, college_id, crc_support) FROM stdin;
1	A0	Busines and Economic	S	Private sponsor	O	1733	A	t	f	1	f
2	A0	Busines and Economic	F	university Scholarship	O	2296	A	t	f	1	f
3	A0	Computer Science and Business Management	F	University Scholarship	O	1822	A	t	f	1	f
4	A0	Busines and Economic	F	University Scholarship	O	1925	A	t	f	1	f
5	A0	Accounting	F	FARG	G	1846	A	t	f	2	f
6	A0	Accounting	F	FARG	G	696	A	t	f	2	f
7	A0	Education	F	FARG	G	1903	A	t	f	2	f
8	A0	Finance	F	FARG	G	2471	A	t	f	2	f
9	A0	General Nursing	F	FARG	G	2028	A	t	f	2	f
10	A0	General Nursing	F	FARG	G	1567	A	t	f	2	f
11	A0	General Nursing	F	FARG	G	2182	A	t	f	2	f
12	A0	Information  Technology	F	FARG	G	32	A	t	f	2	f
13	A0	Logistic	S	Private sponsor	G	1809	A	t	f	2	f
14	A0	Accounting	S	Private sponsor	O	1923	A	t	f	2	f
15	A0	Information System	S	Private sponsor	O	1505	A	t	f	2	f
16	A0	Information Technology	S	Private sponsor	O	1726	A	t	f	2	f
17	A0	Management	S	Private sponsor	O	2176	A	t	f	2	f
18	A0	Finance	S	Private sponsor	G	689	A	t	f	2	f
19	A0	Finance	S	Private sponsor	G	809	A	t	f	2	f
20	A0	General Nursing	S	Private sponsor	G	2298	A	t	f	2	f
21	A0	General Nursing	S	Private sponsor	G	2339	A	t	f	2	f
22	A0	Information System and Programmer	S	Private sponsor	G	1942	A	t	f	2	f
23	A0	Information Technology	S	Private sponsor	G	2332	A	t	f	2	f
24	A0	Sotfware Engineering	S	Private sponsor	G	1783	A	t	f	2	f
25	A0	Accounting	S	Private sponsor	O	2386	A	t	f	2	f
26	A0	IT Training/Programing	F	university Scholarship	O	2068	A	t	f	2	f
27	A0	Information Technology	F	University Scholarship	O	671	A	t	f	2	f
28	A0	Sotfware Engineering	F	University Scholarship	O	666	A	t	f	2	f
29	A0	International Business and Trade	F	Mandella Scholarship	G	44	A	t	f	3	f
30	A0	Social Science	F	Mandella Scholarship	G	42	A	t	f	3	f
31	A0	Technology Enginering	S	Private sponsor	G	2242	A	t	f	3	f
32	A0	Accounting	S	Private sponsor	O	2167	A	t	f	3	f
33	A0	Social Science	S	Private sponsor	O	1572	A	t	f	3	f
34	A0	Computer Science	F	REB	O	2211	A	t	f	3	f
35	A0	Law	F	University Scholarship	D	2236	A	t	f	3	f
36	A0	Global Challenges	F	University Scholarship	G	1642	A	t	f	3	f
37	A0	Graduated from International Business and Trade	F	University Scholarship	G	1977	A	t	f	3	f
38	A0	International Business and Trade	F	University Scholarship	G	48	A	t	f	3	f
39	A0	International Business and Trade	F	University Scholarship	G	2491	A	t	f	3	f
40	A0	International Business and Trade	F	University Scholarship	G	2108	A	t	f	3	f
41	A0	International Business and Trade	F	University Scholarship	G	1967	A	t	f	3	f
42	A0	Social Science	F	University Scholarship	G	1565	A	t	f	3	f
43	A0	Social Science	F	University Scholarship	G	2036	A	t	f	3	f
44	A0	Business	F	University Scholarship	O	2265	A	t	f	3	f
45	A0	Business and Economic	F	university Scholarship	O	2241	A	t	f	3	f
46	A0	Climate change	F	University Scholarship	O	1522	A	t	f	3	f
47	A0	Law	F	university Scholarship	O	2370	A	t	f	3	f
48	A0	Policy Making and Advocacy	F	university Scholarship	O	2516	A	t	f	3	f
49	A0	BSC. (Hons) International Business & Trade (IBT)	F	University Scholarship	O	2340	A	t	f	3	f
50	A0	Entrepreneurial Leadership	F	University Scholarship	O	80	A	t	f	3	f
51	A0	Entrepreneurial Leadership	F	University Scholarship	O	87	A	t	f	3	f
52	A0	Entrepreneurial Leadership	F	University Scholarship	O	1445	A	t	f	3	f
53	A0	Entrepreneurial Leadership	F	University Scholarship	O	1548	A	t	f	3	f
54	A0	Entrepreneurial Leadership	F	University Scholarship	O	1778	A	t	f	3	f
55	A0	Entrepreneurial Leadership	F	University Scholarship	O	787	A	t	f	3	f
56	A0	Social Science	F	University Scholarship	O	1509	A	t	f	3	f
57	A0	Social Science	F	University Scholarship	O	1722	A	t	f	3	f
58	A0	Social Science	F	University Scholarship	O	2044	A	t	f	3	f
59	A0	Social Science	F	University Scholarship	O	2062	A	t	f	3	f
60	A0	Social Science	F	University Scholarship	O	2252	A	t	f	3	f
61	A0	Social Science	F	University Scholarship	O	1671	A	t	f	3	f
62	A0	Social Science	F	University Scholarship	O	1725	A	t	f	3	f
63	A0	Social Science	F	University Scholarship	O	1803	A	t	f	3	f
64	A0	Social Science	F	University Scholarship	O	2392	A	t	f	3	f
65	A0	Social Science	F	University Scholarship	O	1449	A	t	f	3	f
66	A0	Social Science	F	University Scholarship	O	1474	A	t	f	3	f
67	A0	Social Science	F	University Scholarship	O	1525	A	t	f	3	f
68	A0	Social Science	F	University Scholarship	O	1600	A	t	f	3	f
69	A0	Social Science	F	University Scholarship	O	2000	A	t	f	3	f
70	A0	Social Science	F	University Scholarship	O	1610	A	t	f	3	f
71	A0	Social Science	F	University Scholarship	O	1950	A	t	f	3	f
72	A0	Social Science	F	University Scholarship	O	2438	A	t	f	3	f
73	A0	Social Science	F	University Scholarship	O	2452	A	t	f	3	f
74	A0	Social Science	F	University Scholarship	O	1526	A	t	f	3	f
75	A0	Social Science	F	University Scholarship	O	1528	A	t	f	3	f
76	A0	Social Science	F	University Scholarship	O	1682	A	t	f	3	f
77	A0	Social Science	F	University Scholarship	O	2441	A	t	f	3	f
78	A0	Social Science	F	University Scholarship	O	2507	A	t	f	3	f
79	A0	Social Science	F	University Scholarship	O	77	A	t	f	3	f
80	A0	Social Science	F	University Scholarship	O	79	A	t	f	3	f
81	A0	Social Science	F	University Scholarship	O	1852	A	t	f	3	f
82	A0	Social Science	F	University Scholarship	O	1577	A	t	f	3	f
83	A0	Social Science	F	University Scholarship	O	1685	A	t	f	3	f
84	A0	Social Science	F	University Scholarship	O	1789	A	t	f	3	f
85	A0	Social Science	F	University Scholarship	O	1694	A	t	f	3	f
86	A0	Social Science	F	University Scholarship	O	2204	A	t	f	3	f
87	A0	Social Science	F	University Scholarship	O	1446	A	t	f	3	f
88	A0	Social Science	F	University Scholarship	O	2429	A	t	f	3	f
89	A0	Computer Science	F	University Scholarship	G	37	A	t	f	4	f
90	A0	Computing	F	University Scholarship	G	1858	A	t	f	4	f
91	A0	International Relation	F	University Scholarship	G	1866	A	t	f	5	f
92	A0	Piloting	F	MINADEF	G	38	A	t	f	6	f
93	A0	Information Technology	S	Private sponsor	D	2026	A	t	f	7	f
94	A0	Information Technology	S	Private sponsor	D	8	A	t	f	7	f
95	A1	Business Management and Entrepreneurship	S	Private sponsor	G	2284	A	t	f	7	f
96	A1	Business Management and Entrepreneurship	S	Private sponsor	G	2411	A	t	f	7	f
97	A1	Business Management and Entrepreneurship	S	Private sponsor	G	2470	A	t	f	7	f
98	A0	Information Technology	S	Private sponsor	G	721	A	t	f	7	f
99	A1	Information Technology	S	Private sponsor	G	2419	A	t	f	7	f
100	A1	Information Technology	S	Private sponsor	G	755	A	t	f	7	f
101	A1	Information Technology	S	Private sponsor	G	1926	A	t	f	7	f
102	A1	Information Technology	S	Private sponsor	G	1779	A	t	f	7	f
103	A1	Information Technology	S	Private sponsor	G	2079	A	t	f	7	f
104	A0	Information Technology	S	Private sponsor	G	127	A	t	f	7	f
105	A0	Information Technology	S	Private sponsor	G	104	A	t	f	7	f
106	A0	Information Technology	S	Private sponsor	G	1695	A	t	f	7	f
107	A0	Information Technology	S	Private sponsor	G	1818	A	t	f	7	f
108	A0	Information Technology	S	Private sponsor	G	1480	A	t	f	7	f
109	A0	Hospitality Management	S	Private sponsor	G	1888	A	t	f	7	f
110	A0	Hospitality Management	S	Private sponsor	G	2472	A	t	f	7	f
111	A0	Dropped out Hospitality Management	F	University Scholarship	D	2432	A	t	f	7	f
112	A0	Hospitality Management	F	University Scholarship	D	763	A	t	f	7	f
113	A1	Business and Management	F	University Scholarship	G	2327	A	t	f	7	f
114	A1	Business and Management	F	University Scholarship	G	2393	A	t	f	7	f
115	A0	Business Management and Entrepreneurship	F	University Scholarship	G	2522	A	t	f	7	f
116	A0	Business Management and Entrepreneurship	F	University Scholarship	G	732	A	t	f	7	f
117	A0	Business Management and Entrepreneurship	F	University Scholarship	G	1912	A	t	f	7	f
118	A0	Business Management and Entrepreneurship	F	University Scholarship	G	694	A	t	f	7	f
119	A0	Business Management and Entrepreneurship	F	University Scholarship	G	2377	A	t	f	7	f
120	A0	Business Management and Entrepreneurship	F	University Scholarship	G	1970	A	t	f	7	f
121	A1	Business Management and Entrepreneurship	F	University Scholarship	G	130	A	t	f	7	f
122	A1	Business Management and Entrepreneurship	F	University Scholarship	G	133	A	t	f	7	f
123	A1	Business Management and Entrepreneurship	F	University Scholarship	G	801	A	t	f	7	f
124	A1	Business Management and Entrepreneurship	F	University Scholarship	G	1916	A	t	f	7	f
125	A1	Business Management and Entrepreneurship	F	University Scholarship	G	752	A	t	f	7	f
126	A1	Business Management and Entrepreneurship	F	University Scholarship	G	2514	A	t	f	7	f
127	A1	Business Management and Entrepreneurship	F	University Scholarship	G	707	A	t	f	7	f
128	A1	Business Management and Entrepreneurship	F	University Scholarship	G	2431	A	t	f	7	f
129	A1	Business Management and Entrepreneurship	F	University Scholarship	G	2531	A	t	f	7	f
130	A1	Business Management and Entrepreneurship	F	University Scholarship	G	2352	A	t	f	7	f
131	A0	Business Management and Entrepreneurship	F	University Scholarship	G	123	A	t	f	7	f
132	A0	Business Management and Entrepreneurship	F	University Scholarship	G	2196	A	t	f	7	f
133	A0	Business Management and Entrepreneurship	F	University Scholarship	G	18	A	t	f	7	f
134	A0	Business Management and Entrepreneurship	F	University Scholarship	G	1730	A	t	f	7	f
135	A0	Business Management and Entrepreneurship	F	University Scholarship	G	1503	A	t	f	7	f
136	A0	Business Management and Entrepreneurship	F	University Scholarship	G	1538	A	t	f	7	f
137	A0	Business Management and Entrepreneurship	F	University Scholarship	G	2271	A	t	f	7	f
138	A0	Business Management and Entrepreneurship	F	University Scholarship	G	2270	A	t	f	7	f
139	A0	Finance	F	University Scholarship	G	1531	A	t	f	7	f
140	A0	Hospitality Management	F	University Scholarship	G	160	A	t	f	7	f
141	A0	Hospitality Management	F	University Scholarship	G	727	A	t	f	7	f
142	A0	Hospitality Management	F	University Scholarship	G	1482	A	t	f	7	f
143	A0	Hospitality Management	F	University Scholarship	G	2269	A	t	f	7	f
144	A0	Hospitality Management	F	University Scholarship	G	2383	A	t	f	7	f
145	A0	Hospitality Management	F	University Scholarship	G	2098	A	t	f	7	f
146	A0	Hospitality Management	F	University Scholarship	G	1823	A	t	f	7	f
147	A0	Hospitality Management	F	University Scholarship	G	1898	A	t	f	7	f
148	A0	Hospitality Management	F	University Scholarship	G	603	A	t	f	7	f
149	A0	Hospitality Management	F	University Scholarship	G	2123	A	t	f	7	f
150	A0	Hospitality Management	F	University Scholarship	G	2106	A	t	f	7	f
151	A0	Hospitality Management	F	University Scholarship	G	147	A	t	f	7	f
152	A0	Hospitality Management	F	University Scholarship	G	154	A	t	f	7	f
153	A0	Hospitality Management	F	University Scholarship	G	740	A	t	f	7	f
154	A0	Hospitality Management	F	University Scholarship	G	2422	A	t	f	7	f
155	A0	Hospitality Management	F	University Scholarship	G	2477	A	t	f	7	f
156	A0	Hospitality Management	F	University Scholarship	G	695	A	t	f	7	f
157	A0	Hospitality Management	F	University Scholarship	G	761	A	t	f	7	f
158	A0	Hospitality Management	F	University Scholarship	G	762	A	t	f	7	f
159	A0	Hospitality Management	F	University Scholarship	G	765	A	t	f	7	f
160	A0	Hospitality Management	F	University Scholarship	G	768	A	t	f	7	f
161	A0	Hospitality Management	F	University Scholarship	G	769	A	t	f	7	f
162	A0	Hospitality Management	F	University Scholarship	G	1570	A	t	f	7	f
163	A0	Hospitality Management	F	University Scholarship	G	1664	A	t	f	7	f
164	A0	Hospitality Management	F	University Scholarship	G	2189	A	t	f	7	f
165	A0	Hospitality Management	F	University Scholarship	G	1536	A	t	f	7	f
166	A0	Hospitality Management	F	University Scholarship	G	1960	A	t	f	7	f
167	A0	Hospitality Management	F	University Scholarship	G	2007	A	t	f	7	f
168	A0	Hospitality Management	F	University Scholarship	G	2404	A	t	f	7	f
169	A0	Hospitality Management	F	University Scholarship	G	2475	A	t	f	7	f
170	A0	Hospitality Management	F	University Scholarship	G	1900	A	t	f	7	f
171	A0	Hospitality Management	F	University Scholarship	G	1914	A	t	f	7	f
172	A0	Hospitality Management	F	University Scholarship	G	2380	A	t	f	7	f
173	A0	Hospitality Management	F	University Scholarship	G	2403	A	t	f	7	f
174	A0	Hospitality Management	F	University Scholarship	G	2428	A	t	f	7	f
175	A1	Hospitality Management	F	University Scholarship	G	2359	A	t	f	7	f
176	A1	Hospitality Management	F	University Scholarship	G	1906	A	t	f	7	f
177	A1	Hospitality Management	F	University Scholarship	G	2307	A	t	f	7	f
178	A1	Hospitality Management	F	University Scholarship	G	14	A	t	f	7	f
179	A1	Hospitality Management	F	University Scholarship	G	20	A	t	f	7	f
180	A1	Hospitality Management	F	University Scholarship	G	1983	A	t	f	7	f
181	A1	Hospitality Management	F	University Scholarship	G	2503	A	t	f	7	f
182	A1	Hospitality Management	F	University Scholarship	G	1660	A	t	f	7	f
183	A1	Hospitality Management	F	University Scholarship	G	2398	A	t	f	7	f
184	A1	Hospitality Management	F	University Scholarship	G	2449	A	t	f	7	f
185	A0	Hospitality Management	F	University Scholarship	G	124	A	t	f	7	f
186	A0	Hospitality Management	F	University Scholarship	G	136	A	t	f	7	f
187	A0	Hospitality Management	F	University Scholarship	G	1678	A	t	f	7	f
188	A0	Hospitality Management	F	University Scholarship	G	2495	A	t	f	7	f
189	A0	Hospitality Management	F	University Scholarship	G	1989	A	t	f	7	f
190	A0	Hospitality Management	F	University Scholarship	G	2206	A	t	f	7	f
191	A0	Hospitality Management	F	University Scholarship	G	1895	A	t	f	7	f
192	A0	Hospitality Management	F	University Scholarship	G	13	A	t	f	7	f
193	A0	Hospitality Management	F	University Scholarship	G	748	A	t	f	7	f
194	A0	Hospitality Management	F	University Scholarship	G	1964	A	t	f	7	f
195	A0	Human Ressource Management	F	University Scholarship	G	2397	A	t	f	7	f
196	A0	Information  Technology	F	University Scholarship	G	2337	A	t	f	7	f
197	A0	Information System	F	University Scholarship	G	767	A	t	f	7	f
198	A0	Information System	F	University Scholarship	G	774	A	t	f	7	f
199	A1	Information System	F	University Scholarship	G	10	A	t	f	7	f
200	A0	Information System	F	University Scholarship	G	128	A	t	f	7	f
201	A0	Information System	F	University Scholarship	G	794	A	t	f	7	f
202	A0	Information System	F	University Scholarship	G	2313	A	t	f	7	f
203	A0	Information System	F	University Scholarship	G	2483	A	t	f	7	f
204	A0	Information Technology	F	University Scholarship	G	153	A	t	f	7	f
205	A0	Information Technology	F	University Scholarship	G	683	A	t	f	7	f
206	A0	Information Technology	F	University Scholarship	G	2395	A	t	f	7	f
207	A0	International Hotel Management	F	University Scholarship	G	1863	A	t	f	7	f
208	A1	Information Technology	F	University Scholarship	G	1617	A	t	f	7	f
209	A1	Business and Economic	F	University Scholarship	G	1799	A	t	f	7	f
210	A0	International Business croos border e-commerce	F	REB	G	2208	A	t	f	8	f
211	A0	International Business croos border e-commerce	F	REB	O	103	A	t	f	8	f
212	A0	Business and Economic	F	university Scholarship	G	1745	A	t	f	8	f
213	A0	Economic	F	University Scholarship	G	1680	A	t	f	8	f
214	A0	Economic	F	University Scholarship	G	1764	A	t	f	8	f
215	A0	International Business croos border e-commerce	F	University Scholarship	O	2064	A	t	f	8	f
216	A0	International Business croos border e-commerce	F	University Scholarship	O	1478	A	t	f	8	f
217	A0	International Business croos border e-commerce	F	University Scholarship	O	2134	A	t	f	8	f
218	A0	International Business croos border e-commerce	F	University Scholarship	O	2142	A	t	f	8	f
219	A0	International Business croos border e-commerce	F	University Scholarship	O	74	A	t	f	8	f
220	A0	International Business croos border e-commerce	F	University Scholarship	O	670	A	t	f	8	f
221	A0	International Business croos border e-commerce	F	University Scholarship	O	1998	A	t	f	8	f
222	A0	International Business croos border e-commerce	F	University Scholarship	O	2149	A	t	f	8	f
223	A0	University Scholarship	F	University Scholarship	G	2300	A	t	f	9	f
224	M	Computer Science	F	REB	G	1724	A	t	f	10	f
225	A0	Mathematics and Actuarial Science	F	Mastercard	G	715	A	t	f	11	f
226	A0	Public Health	F	Mastercard	G	1795	A	t	f	11	f
227	A0	Public Health	F	Mastercard	G	1857	A	t	f	11	f
228	A0	Photography and Movie Editing	F	University Scholarship	G	2169	A	t	f	11	f
229	A0	Computer Science	F	Mastercard	G	1855	A	t	f	12	f
230	A0	Economic	F	Mastercard	G	2102	A	t	f	12	f
231	A0	Information Communication and Technology	F	Mastercard	G	1653	A	t	f	12	f
232	A0	Information Technology Engineering	F	Mastercard	G	2151	A	t	f	12	f
233	A0	Information Communication and Technology	F	REB	G	2455	A	t	f	12	f
234	A0	Major of Civil Engineering	F	University Scholarship	G	575	A	t	f	13	f
235	A0	Information Technology Engineering	F	University Scholarship	O	1472	A	t	f	14	f
236	M	International Business with Economic Minor  and Poverty Studies/Master's in Development Engineering	F	University Scholarship	G	731	A	t	f	15	f
237	A0	Economic	F	University Scholarship	G	1669	A	t	f	16	f
238	A0	Information System and Programmer	F	University Scholarship	O	1554	A	t	f	16	f
239	A0	Information System and Programmer	F	University Scholarship	O	1932	A	t	f	16	f
240	M	Computer Science	F	FARG	G	1452	A	t	f	17	f
241	M	Electronic Engineering	F	Mastercard	O	587	A	t	f	17	f
242	M	Computer and Software Engineering	F	REB	G	2124	A	t	f	17	f
243	M	Civil Engineering	F	University Scholarship	O	1909	A	t	f	17	f
244	A0	Education in language	F	FARG	G	2443	A	t	f	18	f
245	A0	Public Health	F	FARG	G	1772	A	t	f	18	f
246	A0	Accounting and Management	F	University Scholarship	O	1836	A	t	f	18	f
247	A0	Public Health	F	University Scholarship	O	2096	A	t	f	18	f
248	A0	Accounting	S	Private sponsor	G	716	A	t	f	19	f
249	A0	Finance	S	Private sponsor	G	122	A	t	f	19	f
250	A0	Accounting	S	Private sponsor	G	2109	A	t	f	20	f
251	A0	Finance	S	Private sponsor	G	1934	A	t	f	20	f
252	A0	Information System	F	University Scholarship	G	2350	A	t	f	21	f
253	C	Language	S	Private sponsor	G	2289	A	t	f	22	f
254	A0	Photography and Movie Editing	F	University Scholarship	G	1831	A	t	f	23	f
255	A0	Nautical Science	F	MINEFRA	G	2170	A	t	f	24	f
256	A1	Business Management and Entrepreneurship	S	Private sponsor	G	94	A	t	f	25	f
257	A1	Business Management and Entrepreneurship	S	Private sponsor	G	1748	A	t	f	25	f
258	A1	Business Management and Entrepreneurship	S	Private sponsor	G	2302	A	t	f	25	f
259	A1	Information System	S	Private sponsor	G	1494	A	t	f	25	f
260	A1	Information System	S	Private sponsor	G	2039	A	t	f	25	f
261	A1	IT Training/Programing	S	Private sponsor	G	2513	A	t	f	25	f
262	A1	Information System	S	Private sponsor	G	2156	A	t	f	25	f
263	A1	Information System	S	Private sponsor	G	2168	A	t	f	25	f
264	A1	Information System	S	Private sponsor	G	2225	A	t	f	25	f
265	A1	Information System	S	Private sponsor	G	97	A	t	f	25	f
266	A1	Information System	S	Private sponsor	G	98	A	t	f	25	f
267	A1	Information System	S	Private sponsor	G	99	A	t	f	25	f
268	A1	Information System	S	Private sponsor	G	1688	A	t	f	25	f
269	A1	Information System	S	Private sponsor	G	2245	A	t	f	25	f
270	A1	Information System	S	Private sponsor	G	1553	A	t	f	25	f
271	A1	Business and Management	F	University Scholarship	G	1486	A	t	f	25	f
272	A1	Business Management and Entrepreneurship	F	University Scholarship	G	1493	A	t	f	25	f
273	A1	Business Management and Entrepreneurship	F	University Scholarship	G	64	A	t	f	25	f
274	A1	Business Management and Entrepreneurship	F	University Scholarship	G	70	A	t	f	25	f
275	A1	Business Management and Entrepreneurship	F	University Scholarship	G	1652	A	t	f	25	f
276	A1	Business Management and Entrepreneurship	F	University Scholarship	G	1686	A	t	f	25	f
277	A1	Business Management and Entrepreneurship	F	university Scholarship	G	2237	A	t	f	25	f
278	A1	Information System	F	University Scholarship	G	2215	A	t	f	25	f
279	A1	Information System	F	University Scholarship	G	1711	A	t	f	25	f
280	A1	Information System	F	University Scholarship	G	2214	A	t	f	25	f
281	A1	IT Training/Programing	F	University Scholarship	G	2126	A	t	f	25	f
282	A1	Supply and procurement management	F	university Scholarship	G	1508	A	t	f	25	f
283	A0	Agriculture	F	Mastercard	G	143	A	t	f	26	f
284	A0	Agriculture	F	Mastercard	G	2354	A	t	f	26	f
285	A0	Agriculture	F	University Scholarship	G	2202	A	t	f	26	f
286	M	Agriculture	F	University Scholarship	G	2274	A	t	f	26	f
287	A0	Multicultural Agriculture	F	University Scholarship	G	1954	A	t	f	26	f
288	A0	Agricultural Science	F	University Scholarship	O	1527	A	t	f	26	f
289	A0	Agriculture	F	University Scholarship	O	17	A	t	f	26	f
290	A0	Finance	S	Private sponsor	G	1741	A	t	f	27	f
291	A0	Accounting	F	university Scholarship	O	2487	A	t	f	27	f
292	A0	Finance	F	University Scholarship	O	2474	A	t	f	27	f
293	A0	Photography and Movie Editing	F	FARG	G	1938	A	t	f	28	f
294	A0	Business Management	S	Private sponsor	O	2034	A	t	f	28	f
295	A0	Finance	S	Private sponsor	O	2217	A	t	f	28	f
296	A0	Business	S	Private sponsor	G	1873	A	t	f	28	f
297	A0	Economic	S	Private sponsor	G	52	A	t	f	28	f
298	A0	Filmmaking and film production	S	Private sponsor	G	2484	A	t	f	28	f
299	A0	Main Tourism and Hotel Management	S	Private sponsor	O	2162	A	t	f	28	f
300	A1	Photography and Movie Editing	F	University Scholarship	G	141	A	t	f	28	f
301	A0	Business Management	F	University Scholarship	O	2534	A	t	f	28	f
302	A0	Communication and Business	F	University Scholarship	O	2250	A	t	f	28	f
303	A0	Filmer Maker	F	University Scholarship	O	2344	A	t	f	28	f
304	A0	Finance	F	University Scholarship	O	2285	A	t	f	28	f
305	A0	Photography and Movie Editing	F	University Scholarship	O	1930	A	t	f	28	f
306	A0	Photography and Movie Editing	F	University Scholarship	O	2335	A	t	f	28	f
307	A0	Photography and Movie Editing	F	University Scholarship	O	2466	A	t	f	28	f
308	A0	Photography and Movie Editing	F	University Scholarship	O	1731	A	t	f	28	f
309	A0	Photography and Movie Editing	F	University Scholarship	O	2530	A	t	f	28	f
310	A0	Photography and Movie Editing	F	University Scholarship	O	1564	A	t	f	28	f
311	A0	Civil Engineering	F	University Scholarship	G	2493	A	t	f	29	f
312	M	Civil Engineering	F	University Scholarship	G	2324	A	t	f	29	f
313	M	Computer and Software Engineering	F	REB	O	588	A	t	f	30	f
314	A0	Piloting	F	MINADEF	G	119	A	t	f	31	f
315	C	Information Technology	F	University Scholarship	G	1622	A	t	f	32	f
316	A0	Information Technology	F	University Scholarship	G	2179	A	t	f	32	f
317	C	Business Management	F	University Scholarship	O	2069	A	t	f	32	f
318	A1	Information Technology	F	University Scholarship	O	1649	A	t	f	32	f
319	A0	Information Technology	S	Private sponsor	O	2171	A	t	f	33	f
320	A0	Information Technology	S	Private sponsor	O	1454	A	t	f	33	f
321	A0	Law	F	FARG	G	1718	A	t	f	34	f
322	A0	Accounting	F	FARG	G	2480	A	t	f	34	f
323	A0	Accounting	F	FARG	G	2115	A	t	f	34	f
324	A0	Economic	F	FARG	G	1894	A	t	f	34	f
325	A0	Finance	F	FARG	G	35	A	t	f	34	f
326	A0	International Relation	F	FARG	G	24	A	t	f	34	f
327	A0	Law	F	FARG	G	1929	A	t	f	34	f
328	A0	Law	F	FARG	G	1910	A	t	f	34	f
329	A0	Management	F	FARG	G	31	A	t	f	34	f
330	A0	Marketing	F	FARG	G	1920	A	t	f	34	f
331	A0	Social Worker	F	FARG	G	2451	A	t	f	34	f
332	A0	none	S	Private sponsor	D	2190	A	t	f	34	f
333	A0	Accounting	S	Private sponsor	G	750	A	t	f	34	f
334	A0	Finance	S	Private sponsor	G	1931	A	t	f	34	f
335	A0	Law	S	Private sponsor	G	2128	A	t	f	34	f
336	A0		S	Private sponsor	G	2295	A	t	f	34	f
337	A0		S	Private sponsor	G	759	A	t	f	34	f
338	A0	Accounting	S	Private sponsor	O	1992	A	t	f	34	f
339	A0	Accounting	S	Private sponsor	G	1901	A	t	f	34	f
340	A0	Economic	S	PRIVATE sponsor	G	2127	A	t	f	34	f
341	A0	Fiance	S	Private sponsor	G	2059	A	t	f	34	f
342	A0	Finance	S	Private sponsor	G	26	A	t	f	34	f
343	A0	Finance	S	Private sponsor	G	1860	A	t	f	34	f
344	A0	Finance	S	Private sponsor	G	580	A	t	f	34	f
345	A0	Finance	S	Private sponsor	G	140	A	t	f	34	f
346	A0	Finance	S	Private sponsor	G	1681	A	t	f	34	f
347	A0	Finance	S	Private sponsor	G	2097	A	t	f	34	f
348	A0	Law	S	Private sponsor	G	152	A	t	f	34	f
349	A0	Law	S	Private sponsor	G	150	A	t	f	34	f
350	A0	Law	S	Private sponsor	G	1842	A	t	f	34	f
351	A0	Law	S	Private sponsor	G	1865	A	t	f	34	f
352	M	Law	S	Private sponsor	G	1801	A	t	f	34	f
353	A0	Law	S	Private sponsor	G	798	A	t	f	34	f
354	A0	Marketing	S	Private sponsor	G	729	A	t	f	34	f
355	A0	Marketing	S	Private sponsor	G	1835	A	t	f	34	f
356	A0		S	Private sponsor	G	27	A	t	f	34	f
357	A0	Hospitality Management	S	Private sponsor	O	2255	A	t	f	34	f
358	A0	Law	S	Private sponsor	O	1605	A	t	f	34	f
359	A0	Finance	F	REB	D	163	A	t	f	34	f
360	A0	Journalism and Communication	F	REB	G	2150	A	t	f	34	f
361	A0	Law	F	REB	G	1805	A	t	f	34	f
362	A0	Information Technology	F	University Scholarship	G	684	A	t	f	34	f
363	A0	Law	F	University Scholarship	G	2258	A	t	f	34	f
364	A0		F	University Scholarship	O	2334	A	t	f	34	f
365	A0	International Hotel Management	F	University Scholarship	G	2385	A	t	f	35	f
366	A0	Journalism and Communication	F	FARG	G	615	A	t	f	36	f
367	A0	Journalism and Communication	F	FARG	G	2220	A	t	f	36	f
368	A0	Journalism and Communication	F	FARG	G	1585	A	t	f	36	f
369	A0	Socialogy	F	FARG	G	2505	A	t	f	36	f
370	A0	Midwifery	S	Private sponsor	O	1497	A	t	f	36	f
371	A0	Midwifery	S	Private sponsor	D	2363	A	t	f	36	f
372	A0	Journalism and Communication	S	Private sponsor	G	2183	A	t	f	36	f
373	A0	Journalism and Communication	S	Private sponsor	G	66	A	t	f	36	f
374	A0	Journalism and Communication	S	Private sponsor	G	1639	A	t	f	36	f
375	A0	Sociology	S	Private sponsor	G	1535	A	t	f	36	f
376	A0	Economic	S	Private sponsor	G	1476	A	t	f	37	f
377	A0	Dropped out	F	FARG	D	1456	A	t	f	38	f
378	A0	Biomedical Laboratory Science	F	FARG	G	2107	A	t	f	38	f
379	A0	Finance	F	FARG	G	2118	A	t	f	38	f
380	A0	Finance and Economic	F	FARG	G	1580	A	t	f	38	f
381	A0	Laboratory	F	FARG	G	1739	A	t	f	38	f
382	A0	Land Administration and Management	F	FARG	G	2396	A	t	f	38	f
383	A0	Land Administration and Management	S	Private sponsor	G	1972	A	t	f	38	f
384	A0	Biotechnology	S	Private sponsor	O	2114	A	t	f	38	f
385	A0	Biotechnology	S	Private sponsor	O	1612	A	t	f	38	f
386	A0	Land Administration and Management	S	Private sponsor	O	1698	A	t	f	38	f
387	A0	Land Administration and Management	S	Private sponsor	O	2407	A	t	f	38	f
388	A0	Finance	S	Private sponsor	D	2308	A	t	f	38	f
389	A0	Land Administration and Management	S	Private sponsor	G	1890	A	t	f	38	f
390	A0	Land Administration and Management	S	Private sponsor	G	1769	A	t	f	38	f
391	A0	Midwfery	S	Private sponsor	G	2306	A	t	f	38	f
392	A0	Law	F	REB	D	67	A	t	f	38	f
393	A0	Midwfery	F	University Scholarship	O	1466	A	t	f	38	f
394	A0	Midwfery	F	University Scholarship	O	2008	A	t	f	38	f
395	A0	Midwfery	F	University Scholarship	O	1571	A	t	f	38	f
396	A0	Business Information and Technology	F	FARG	G	576	A	t	f	39	f
397	A0	Accounting	S	Private sponsor	G	2227	A	t	f	39	f
398	A0	Business Information and Technology	F	University Scholarship	O	2320	A	t	f	39	f
399	A1	Cooking	F	FARG	G	41	A	t	f	40	f
400	A1	Hospitality Management	F	FARG	G	742	A	t	f	40	f
401	A1	Information Communication and Technology	F	FARG	G	2012	A	t	f	40	f
402	A1	Information Communication and Technology	F	FARG	G	2264	A	t	f	40	f
403	A1	Mechanical Engineering	F	FARG	G	2033	A	t	f	40	f
404	A1	Construction Training	S	Private sponsor	G	1963	A	t	f	40	f
405	A1	Hospitality Training	S	Private sponsor	G	1650	A	t	f	40	f
406	C	multimedia	S	Private sponsor	G	1635	A	t	f	40	f
407	A1	IT Training/Programing	S	Private sponsor	O	2445	A	t	f	40	f
408	A1	multimedia	S	Private sponsor	G	2037	A	t	f	40	f
409	A1	Sewing	S	Private sponsor	O	2408	A	t	f	40	f
410	A1	Biomedical Engineering	F	REB	D	105	A	t	f	40	f
411	A1	Information Technology	F	REB	D	687	A	t	f	40	f
412	A1	Information Technology	F	REB	G	2078	A	t	f	40	f
413	A1	Information Technology	F	REB	G	1593	A	t	f	40	f
414	A1	Mining Engineering	F	REB	G	1786	A	t	f	40	f
415	A1	Phographer and Movie Editing	F	University Scholarship	G	1706	A	t	f	40	f
416	A1	Photographer	F	University Scholarship	G	1827	A	t	f	40	f
417	A1	Photography and Movie Editing	F	University Scholarship	G	2158	A	t	f	40	f
418	A1	Photography and Movie Editing	F	University Scholarship	G	1502	A	t	f	40	f
419	A1	Sewing	F	University Scholarship	O	1777	A	t	f	40	f
420	A1	Sewing	F	University Scholarship	O	1732	A	t	f	40	f
421	A0	Government and sustainabillity	F	Embassy Scholarship	G	1804	A	t	f	41	f
422	A0	Leadership	F	University Scholarship	O	2164	A	t	f	41	f
423	A0	Priest	S	Private sponsor	O	1453	A	t	f	42	f
424	A0	Communication	S	Private sponsor	G	2318	A	t	f	43	f
425	A0	Mathematic	F	REB	D	1746	A	t	f	43	f
426	M	Mathematic	F	University Scholarship	G	1825	A	t	f	43	f
427	A0	Hospitality Management	F	WDA	G	159	A	t	f	44	f
428	A0	Hospitality Management	F	WDA	G	589	A	t	f	44	f
429	A0	Hospitality Management	F	WDA	G	2317	A	t	f	44	f
430	A1	Management	S	Private sponsor	O	2094	A	t	f	45	f
431	A1	Management	S	Private sponsor	O	2140	A	t	f	45	f
432	A1	Business Administration and Logistic	F	University Scholarship	G	51	A	t	f	45	f
433	A1	Business Administration and Logistic	F	University Scholarship	G	1798	A	t	f	45	f
434	A1	Business Communication	F	University Scholarship	G	2371	A	t	f	45	f
435	A1	Business Communication	F	University Scholarship	G	2141	A	t	f	45	f
436	A1	Business Communication	F	University Scholarship	G	693	A	t	f	45	f
437	A1	Business Communication	F	University Scholarship	G	61	A	t	f	45	f
438	A1	Business Communication	F	University Scholarship	G	1643	A	t	f	45	f
439	A1	Concentration in Business communication	F	University Scholarship	G	57	A	t	f	45	f
440	A1	Logistic	F	University Scholarship	G	2518	A	t	f	45	f
441	A1	Management/Concentrate in Public Admistration	F	University Scholarship	G	1468	A	t	f	45	f
442	A1	Procument Management	F	University Scholarship	G	737	A	t	f	45	f
443	A1	Bachelor of Art in Management	F	university Scholarship	O	2185	A	t	f	45	f
444	A1	Business Management	F	University Scholarship	O	2509	A	t	f	45	f
445	A1	Business Analytic	F	University Scholarship	O	663	A	t	f	45	f
446	A1	Business Analytic	F	University Scholarship	O	2180	A	t	f	45	f
447	A1	Project Management	F	University Scholarship	O	78	A	t	f	45	f
448	A1	Project Management	F	University Scholarship	O	83	A	t	f	45	f
725	A0	Finance	F	FARG	G	2193	A	t	f	87	f
449	A1	Project Management	F	University Scholarship	O	1808	A	t	f	45	f
450	A1	Project Management	F	University Scholarship	O	682	A	t	f	45	f
451	A1	Project Management	F	University Scholarship	O	1995	A	t	f	45	f
452	A1	Project Management	F	University Scholarship	O	1811	A	t	f	45	f
453	A1	Project Management	F	University Scholarship	O	1460	A	t	f	45	f
454	A1	Project Management	F	University Scholarship	O	1463	A	t	f	45	f
455	A0	Finance and Banking	S	Private sponsor	G	578	A	t	f	46	f
456	A0	Procument Management	S	Private sponsor	G	2374	A	t	f	46	f
457	A0	Nursing	F	Mastercard	O	2116	A	t	f	47	f
458	A0	Finance	S	Private sponsor	G	720	A	t	f	48	f
459	A0	Bachelor of Art	F	University Scholarship	O	1975	A	t	f	49	f
460	A0	Finance	S	Private sponsor	G	1599	A	t	f	50	f
461	A0	Communication	F	University Scholarship	O	1999	A	t	f	51	f
462	A0	Information System	F	University Scholarship	O	59	A	t	f	52	f
463	A0	Business Administration	F	Mastercard	G	602	A	t	f	53	f
464	A0	Computer Science	F	Mastercard	G	1516	A	t	f	53	f
465	A0	Economic and Internation Development studies	F	Mastercard	G	2075	A	t	f	53	f
466	A0	Music	F	Mastercard	G	2210	A	t	f	53	f
467	A0	Social Science	F	Mastercard	G	2464	A	t	f	53	f
468	M	Social Worker	F	Mastercard	G	118	A	t	f	53	f
469	A0	Social Worker	S	Private sponsor	G	2425	A	t	f	53	f
470	A0	Social Worker	F	University Scholarship	G	1720	A	t	f	53	f
471	A0	Social Worker	F	University Scholarship	O	807	A	t	f	53	f
472	A0	Bachelor of Entrepreneurship Leadership	S	Private sponsor	O	2120	A	t	f	54	f
473	A0	Business and Computer Science	F	university Scholarship	O	1666	A	t	f	54	f
474	A0	Information Technology	S	Private sponsor	G	36	A	t	f	55	f
475	A0	Marketing	S	Private sponsor	G	2458	A	t	f	55	f
476	A0	Multimedia Communication	S	Private sponsor	G	2312	A	t	f	55	f
477	A0	Public Health	S	Private sponsor	G	2490	A	t	f	55	f
478	A0	Tourism & Management	S	private sponsor	G	2200	A	t	f	55	f
479	A0	Tourism and technology	S	Private sponsor	G	2048	A	t	f	55	f
480	A0	Travel and Tourism Management	S	Private sponsor	G	2130	A	t	f	55	f
481	A0	Multimedia Communication	F	REB	G	2437	A	t	f	55	f
482	A0	Information Technology	F	University Scholarship	G	1712	A	t	f	55	f
483	A0	Hospitality Management	S	Private sponsor	O	708	A	t	f	56	f
484	A0	Business Management and Internation Business	S	Private sponsor	G	1715	A	t	f	56	f
485	A0	Business and Economic	S	Private sponsor	O	1784	A	t	f	56	f
486	A0	Hospitality Management	S	Private sponsor	O	1821	A	t	f	56	f
487	A0	Hospitality Management	F	University Scholarship	G	2442	A	t	f	56	f
488	A0	Business Information Technology	F	University Scholarship	O	1506	A	t	f	56	f
489	A0	Business Management	F	University Scholarship	O	1854	A	t	f	56	f
490	A0	Communication	F	University Scholarship	O	1670	A	t	f	56	f
491	A0	Hospitality Management	F	University Scholarship	O	1851	A	t	f	56	f
492	A0	Hospitality Management	F	University Scholarship	O	2230	A	t	f	56	f
493	A0	Hospitality Management	F	University Scholarship	O	1717	A	t	f	56	f
494	A0	Hospitality Management	F	University Scholarship	O	2361	A	t	f	56	f
495	A0	Hospitality Management	F	University Scholarship	O	1461	A	t	f	56	f
496	A0	Hospitality Management	F	University Scholarship	O	1750	A	t	f	56	f
497	A0	Hospitality Management	F	University Scholarship	O	2090	A	t	f	56	f
498	A0	Hospitality Management	F	University Scholarship	O	2303	A	t	f	56	f
499	A0	Conmputer Science, French and statistic	F	University Scholarship	G	146	A	t	f	57	f
500	A0	Economic	F	University Scholarship	G	770	A	t	f	57	f
501	A0	Economic	F	University Scholarship	O	2004	A	t	f	58	f
502	A0	Computer engineering	S	Private sponsor	O	802	A	t	f	59	f
503	A0	Procument Management	F	FARG	G	1623	A	t	f	60	f
504	A0	Rural Development	S	Private sponsor	O	2035	A	t	f	60	f
505	A0	Theology and Religious Studies	S	Private sponsor	G	2201	A	t	f	60	f
506	A0	Finance and Economic	S	Private sponsor	G	2072	A	t	f	61	f
507	A0	Business Analyst	F	University Scholarship	G	797	A	t	f	62	f
508	A0	Communication	S	Private sponsor	O	1491	A	t	f	63	f
509	A0	Agriculture	F	University Scholarship	G	12	A	t	f	63	f
510	A0	Agriculture	F	University Scholarship	G	95	A	t	f	63	f
511	A0	Agriculture	F	University Scholarship	G	106	A	t	f	63	f
512	A0	Agriculture	F	University Scholarship	G	749	A	t	f	63	f
513	A0	Agriculture	F	University Scholarship	G	1552	A	t	f	63	f
514	A0	Agriculture	F	University Scholarship	G	1773	A	t	f	63	f
515	A0	Agriculture	F	University Scholarship	G	1973	A	t	f	63	f
516	A0	Agriculture	F	University Scholarship	G	2461	A	t	f	63	f
517	A0	Agriculture	F	University Scholarship	G	2489	A	t	f	63	f
518	A0	Agriculture	F	University Scholarship	G	1719	A	t	f	63	f
519	A0	Agriculture	F	University Scholarship	G	2145	A	t	f	63	f
520	A0	Agriculture	F	University Scholarship	G	2216	A	t	f	63	f
521	A0	Agriculture	F	University Scholarship	G	1729	A	t	f	63	f
522	A0	Agriculture	F	University Scholarship	G	1596	A	t	f	63	f
523	A0	Agriculture	F	University Scholarship	G	1867	A	t	f	63	f
524	A0	Internal economics	F	university Scholarship	G	1737	A	t	f	63	f
525	A0	IT Training/Programing	F	University Scholarship	G	1692	A	t	f	63	f
526	A0	Economic	F	University Scholarship	G	1583	A	t	f	64	f
527	A0	Information System	F	University Scholarship	G	25	A	t	f	64	f
528	A0	Information System	F	University Scholarship	O	2492	A	t	f	64	f
529	M	Mechanical Engineering	F	MINADEF	G	1797	A	t	f	65	f
530	A0	Mechanical Engineering	S	Private sponsor	G	55	A	t	f	65	f
531	A0	Marketing	S	Private sponsor	G	1550	A	t	f	65	f
532	A0	Finance	F	REB	G	2173	A	t	f	65	f
533	A0	Mechanical Engineering	F	University Scholarship	O	1556	A	t	f	65	f
534	A0	Mechanical Engineering	F	University Scholarship	O	669	A	t	f	65	f
535	A0	Mechanical Engineering	F	University Scholarship	O	1549	A	t	f	65	f
536	A0	Information Seculity	F	Rwanda Nation Police	G	1955	A	t	f	66	f
537	A0	Information Technology	F	Rwanda Nation Police	G	2304	A	t	f	66	f
538	A0	Information Technology	F	Rwanda Nation Police	G	1979	A	t	f	66	f
539	A0	Law	F	University Scholarship	O	1776	A	t	f	66	f
540	A0	Law	F	University Scholarship	O	662	A	t	f	66	f
541	A0	Law	F	University Scholarship	O	1953	A	t	f	66	f
542	A0	Construction Management	F	FARG	D	771	A	t	f	67	f
543	A0	Information System	F	University Scholarship	G	125	A	t	f	68	f
544	A0	Computer Science	F	University Scholarship	O	1603	A	t	f	68	f
545	A0	Computer Science	F	University Scholarship	O	1475	A	t	f	68	f
546	A0	Information System	F	University Scholarship	O	1754	A	t	f	69	f
547	A0	Information System	F	University Scholarship	O	1447	A	t	f	69	f
548	A0	Majoring in Psychology with a minor in Women'S Studies	F	University Scholarship	G	2481	A	t	f	70	f
549	A0	Accounting	F	FARG	G	2198	A	t	f	71	f
550	A0	Business Communication	F	University Scholarship	G	2093	A	t	f	71	f
551	A0	Logistic	F	University Scholarship	G	1753	A	t	f	71	f
552	A0	Management with Concentration in Public Administration	F	University Scholarship	G	2019	A	t	f	71	f
553	A0	Management/Concentrate in Logisitc	F	University Scholarship	G	724	A	t	f	71	f
554	A0	Management/Concentrate in Public Admistration	F	University Scholarship	G	2409	A	t	f	71	f
555	A0	Civil Engineering	F	FARG	G	1961	A	t	f	72	f
556	A0	Finance	F	FARG	G	1755	A	t	f	73	f
557	A0	General Medecin	F	FARG	G	2043	A	t	f	73	f
558	A0	Business Analyst	F	University Scholarship	G	2229	A	t	f	74	f
559	A0	Information System	F	University Scholarship	G	46	A	t	f	75	f
560	A0	Information System	F	University Scholarship	O	2253	A	t	f	75	f
561	A0	Information System	F	University Scholarship	O	2178	A	t	f	75	f
562	A0	Information System	F	University Scholarship	O	1529	A	t	f	75	f
563	A0	Information System	F	University Scholarship	O	2209	A	t	f	76	f
564	A0	Information System	F	University Scholarship	O	673	A	t	f	77	f
565	A0	Information System	F	University Scholarship	O	661	A	t	f	77	f
566	A0	Information System	F	University Scholarship	O	1614	A	t	f	77	f
567	A0	Finance	F	FARG	D	1907	A	t	f	87	f
568	M	General Nursing	F	FARG	G	2137	A	t	f	87	f
569	A0		S	Private sponsor	G	1624	A	t	f	87	f
570	A0	Journalism and Communication	F	REB	G	96	A	t	f	87	f
571	A0	Nursing	F	REB	G	1514	A	t	f	87	f
572	M	Economic	F	Mastercard	G	1838	A	t	f	78	f
573	M	Forest and Conservation Engineering	F	Mastercard	G	2095	A	t	f	78	f
574	M	Natural Ressources Conservation	F	Mastercard	G	1986	A	t	f	78	f
575	M	Resources, Environment and Sustainability	F	Mastercard	G	1945	A	t	f	78	f
576	M	Social Worker	F	University Scholarship	G	2343	A	t	f	78	f
577	A0	Social Worker	F	University Scholarship	O	1980	A	t	f	78	f
578	A0	General Nursing	F	FARG	G	608	A	t	f	79	f
579	A0	General Nursing	F	FARG	G	614	A	t	f	79	f
580	A0	General Nursing	F	FARG	G	1924	A	t	f	79	f
581	A0	General Nursing	F	FARG	G	2326	A	t	f	79	f
582	A0	Nursing	F	FARG	G	158	A	t	f	79	f
583	A0	Medicine	F	University Scholarship	O	2459	A	t	f	80	f
584	A0	Hospitality Management	F	University Scholarship	G	581	A	t	f	81	f
585	A0	Finance	F	FARG	D	728	A	t	f	82	f
586	A0	Finance	F	FARG	G	1584	A	t	f	82	f
587	A0	Finance	F	FARG	G	1878	A	t	f	82	f
588	A0	Information Technology	F	FARG	G	39	A	t	f	82	f
589	A0	Marketing	F	FARG	G	723	A	t	f	82	f
590	A0	Marketing	S	Private sponsor	G	760	A	t	f	82	f
591	A0	Marketing	S	Private sponsor	G	2416	A	t	f	82	f
592	A0	Marketing	S	Private sponsor	G	2219	A	t	f	82	f
593	A0	Marketing	S	Private sponsor	G	1697	A	t	f	82	f
594	A0	Marketing	S	Private sponsor	G	1845	A	t	f	82	f
595	A0	Marketing	S	Private sponsor	G	706	A	t	f	82	f
596	A0	Accounting	S	Private sponsor	O	1602	A	t	f	82	f
597	A0	Accounting	S	Private sponsor	O	1993	A	t	f	82	f
598	A0	Finance	S	Private sponsor	O	1935	A	t	f	82	f
599	A0	IT Training/Programing	S	Private sponsor	O	2259	A	t	f	82	f
600	A0	Marketing	S	Private sponsor	O	1702	A	t	f	82	f
601	A0	Marketing	S	Private sponsor	O	2042	A	t	f	82	f
602	A0	Marketing	S	Private sponsor	O	2436	A	t	f	82	f
603	A0	Finance	S	Private sponsor	D	2231	A	t	f	82	f
604	A0	Accounting	S	Private sponsor	G	65	A	t	f	82	f
605	A0	Accounting	S	Private sponsor	G	62	A	t	f	82	f
606	A0	Finance	S	Private sponsor	G	2226	A	t	f	82	f
607	A0	Finance	S	Private sponsor	G	717	A	t	f	82	f
608	A0	Finance	S	Private sponsor	G	2132	A	t	f	82	f
609	A0	Finance	S	Private sponsor	G	2261	A	t	f	82	f
610	A0	Finance	S	Private sponsor	G	1707	A	t	f	82	f
611	A0	Finance	S	Private sponsor	G	1738	A	t	f	82	f
612	A0	Finance	S	Private sponsor	G	686	A	t	f	82	f
613	A0	Law	S	Private sponsor	G	688	A	t	f	82	f
614	A0	Marketing	S	Private sponsor	G	1756	A	t	f	82	f
615	A0	Marketing	S	Private sponsor	G	1759	A	t	f	82	f
616	M	Marketing	S	Private sponsor	G	2105	A	t	f	82	f
617	A0	Marketing	S	Private sponsor	G	1956	A	t	f	82	f
618	M	Tourism & Management	S	Private sponsor	G	2277	A	t	f	82	f
619	A0	Finance	S	Private sponsor	O	1471	A	t	f	82	f
620	A0	Information System	S	Private sponsor	O	2205	A	t	f	82	f
621	A0	Law	S	Private sponsor	O	1606	A	t	f	82	f
622	A0	Marketing	S	Private sponsor	O	1810	A	t	f	82	f
623	A0	Accounting	F	REB	O	1467	A	t	f	82	f
624	A0	Accounting	F	REB	O	1709	A	t	f	82	f
625	A0	Business Management and Entrepreneurship	F	University Scholarship	G	1555	A	t	f	82	f
626	A0	Finance	F	University Scholarship	G	1762	A	t	f	82	f
627	A0	Business Management and Entrepreneurship	F	university Scholarship	O	1645	A	t	f	82	f
628	A0	Hospitality Management	F	University Scholarship	O	2360	A	t	f	82	f
629	A0	Information System	F	University Scholarship	O	2088	A	t	f	82	f
630	A0	IT Training/Programing	F	university Scholarship	O	1569	A	t	f	82	f
631	A0	Business Information Technology	F	University Scholarship	O	665	A	t	f	82	f
632	A0	Marketing	F	University Scholarship	O	1790	A	t	f	82	f
633	A0	Marketing	F	University Scholarship	O	1651	A	t	f	82	f
634	A0	Marketing	F	University Scholarship	O	2342	A	t	f	82	f
635	A0	Marketing	F	University Scholarship	O	1532	A	t	f	82	f
636	A0	Marketing	F	University Scholarship	O	1679	A	t	f	82	f
637	A0	Marketing	F	University Scholarship	O	1882	A	t	f	82	f
638	A0	Marketing and Selling	F	FARG	D	1734	A	t	f	83	f
639	A0	Marketing and Selling	F	FARG	D	1513	A	t	f	83	f
640	A0	Accounting	F	FARG	G	1728	A	t	f	83	f
641	A0	Finance	F	FARG	G	1927	A	t	f	83	f
642	A0	Finance	F	FARG	G	2440	A	t	f	83	f
643	A0	Finance	F	FARG	G	766	A	t	f	83	f
644	A0	Law	F	FARG	G	2233	A	t	f	83	f
645	A0	Marketing	S	Private sponsor	G	1943	A	t	f	83	f
646	A0	Law	S	Private sponsor	O	2417	A	t	f	83	f
647	A0	Marketing	S	Private sponsor	O	1465	A	t	f	83	f
648	A0	Accounting	S	Private sponsor	G	2212	A	t	f	83	f
649	A0	Business administration	S	private sponsor	G	1962	A	t	f	83	f
650	A0	Fiance	S	Private sponsor	G	1884	A	t	f	83	f
651	A0	Finance	S	Private sponsor	G	1604	A	t	f	83	f
652	A0	Marketing	S	Private sponsor	G	612	A	t	f	83	f
653	A0	Marketing	S	Private sponsor	G	1974	A	t	f	83	f
654	A0	Marketing	S	Private sponsor	G	744	A	t	f	83	f
655	A0	Marketing and Selling	S	Private sponsor	G	738	A	t	f	83	f
656	A0	Hospitality Management	F	university Scholarship	G	2016	A	t	f	83	f
657	A0	Marketing and Selling	F	University Scholarship	O	1590	A	t	f	83	f
658	A0	Marketing and Selling	F	University Scholarship	O	1659	A	t	f	83	f
659	A0	Marketing and Selling	F	University Scholarship	O	1937	A	t	f	83	f
660	A0	Marketing and Selling	F	University Scholarship	O	2266	A	t	f	83	f
661	A0	Marketing and Selling	F	University Scholarship	O	1620	A	t	f	83	f
662	A0	Agri-business	F	University Scholarship	G	2049	A	t	f	84	f
663	A0	Agri-business	F	University Scholarship	G	2112	A	t	f	84	f
664	A0	Agri-business	F	University Scholarship	G	1704	A	t	f	84	f
665	A0	Agri-business	F	University Scholarship	G	1819	A	t	f	84	f
666	M	Agri-business	F	University Scholarship	G	2278	A	t	f	84	f
667	A0	Agriculture	F	University Scholarship	G	2166	A	t	f	84	f
668	M	Agriculture	F	University Scholarship	G	2502	A	t	f	84	f
669	A0	Integrated Science	F	University Scholarship	G	2085	A	t	f	84	f
670	M	Business Administration	F	University Scholarship	G	114	A	t	f	85	f
671	A0	Finance	F	REB	G	2517	A	t	f	86	f
672	A0	Finance	F	University Scholarship	O	1457	A	t	f	86	f
673	A0	Clinical Psychology	F	Clinical Psychologiy	G	2022	A	t	f	87	f
674	A0		F	FARG	D	594	A	t	f	87	f
675	A0		F	FARG	D	2099	A	t	f	87	f
676	A0	Accounting	F	FARG	G	591	A	t	f	87	f
677	A0	Accounting	F	FARG	G	593	A	t	f	87	f
678	A0	Accounting	F	FARG	G	601	A	t	f	87	f
679	A0	Accounting	F	FARG	G	1862	A	t	f	87	f
680	A0	Accounting	F	FARG	G	2379	A	t	f	87	f
681	A0	Accounting	F	FARG	G	2413	A	t	f	87	f
682	A0	Accounting	F	FARG	G	736	A	t	f	87	f
683	A0	Accounting	F	FARG	G	2520	A	t	f	87	f
684	A0	Accounting	F	FARG	G	2358	A	t	f	87	f
685	A0	Accounting	F	FARG	G	584	A	t	f	87	f
686	A0	Agri-Business	F	FARG	G	2249	A	t	f	87	f
687	M	Agri-Business	F	FARG	G	2073	A	t	f	87	f
688	A0	Bio-Medical Laboratory	F	FARG	G	2262	A	t	f	87	f
689	A0	Business Information and Technology	F	FARG	G	574	A	t	f	87	f
690	A0	Civil Engineering	F	FARG	G	597	A	t	f	87	f
691	A0	Computer Science	F	FARG	G	1877	A	t	f	87	f
692	C	CPA	F	FARG	G	584	A	t	f	87	f
693	A0	Crop Production	F	FARG	G	112	A	t	f	87	f
694	A0	Crop Production	F	FARG	G	161	A	t	f	87	f
695	A0	Crop Production	F	FARG	G	1557	A	t	f	87	f
696	A0	Crop Production	F	FARG	G	2283	A	t	f	87	f
697	A0	Crop Production	F	FARG	G	1793	A	t	f	87	f
698	A0	Crop Production	F	FARG	G	2061	A	t	f	87	f
699	A0	Economic	F	FARG	G	110	A	t	f	87	f
700	A0	Economic	F	FARG	G	117	A	t	f	87	f
701	A0	Economic	F	FARG	G	164	A	t	f	87	f
702	A0	Economic	F	FARG	G	599	A	t	f	87	f
703	A0	Economic	F	FARG	G	600	A	t	f	87	f
704	A0	Economic	F	FARG	G	1592	A	t	f	87	f
705	A0	Economic	F	FARG	G	2031	A	t	f	87	f
706	A0	Economic	F	FARG	G	30	A	t	f	87	f
707	A0	Economic	F	FARG	G	28	A	t	f	87	f
708	A0	Economic	F	FARG	G	2456	A	t	f	87	f
709	A0	Economic	F	FARG	G	1946	A	t	f	87	f
710	A0	Economic	F	FARG	G	139	A	t	f	87	f
711	A0	Economic	F	FARG	G	2338	A	t	f	87	f
712	A0	Economic	F	FARG	G	2400	A	t	f	87	f
713	A0	Economic	F	FARG	G	2144	A	t	f	87	f
714	A0	English education	F	FARG	G	2494	A	t	f	87	f
715	A0	English Language	F	FARG	G	1743	A	t	f	87	f
716	A0	Finance	F	FARG	G	116	A	t	f	87	f
717	A0	Finance	F	FARG	G	598	A	t	f	87	f
718	A0	Finance	F	FARG	G	2086	A	t	f	87	f
719	A0	Finance	F	FARG	G	1512	A	t	f	87	f
720	A0	Finance	F	FARG	G	1631	A	t	f	87	f
721	A0	Finance	F	FARG	G	2181	A	t	f	87	f
722	A0	Finance	F	FARG	G	2323	A	t	f	87	f
723	A0	Finance	F	FARG	G	2525	A	t	f	87	f
724	A0	Finance	F	FARG	G	1609	A	t	f	87	f
726	A0	Finance	F	FARG	G	1758	A	t	f	87	f
727	A0	Finance	F	FARG	G	1815	A	t	f	87	f
728	A0	Finance	F	FARG	G	2476	A	t	f	87	f
729	A0	Finance	F	FARG	G	583	A	t	f	87	f
730	A0	Finance	F	FARG	G	606	A	t	f	87	f
731	A0	Finance	F	FARG	G	1749	A	t	f	87	f
732	A0	Finance	F	FARG	G	1969	A	t	f	87	f
733	A0	Finance	F	FARG	G	773	A	t	f	87	f
734	A0	Finance	F	FARG	G	1747	A	t	f	87	f
735	A0	General Nursing	F	FARG	G	1534	A	t	f	87	f
736	A0	General Nursing	F	FARG	G	2321	A	t	f	87	f
737	A0	Geography	F	FARG	G	2415	A	t	f	87	f
738	A0	Geography	F	FARG	G	1802	A	t	f	87	f
739	A0	Governance and Leardership	F	FARG	G	1708	A	t	f	87	f
740	A0	Governance and Leardership	F	FARG	G	2528	A	t	f	87	f
741	A0	History	F	FARG	G	735	A	t	f	87	f
742	A0	Horticulture	F	FARG	G	1826	A	t	f	87	f
743	A0	Human Ressource Management	F	FARG	G	151	A	t	f	87	f
744	A0	Information System	F	FARG	G	1658	A	t	f	87	f
745	A0	Information Technology	F	FARG	G	115	A	t	f	87	f
746	A0	Information Technology	F	FARG	G	156	A	t	f	87	f
747	A0	Journalism and Communication	F	FARG	G	2390	A	t	f	87	f
748	A0	Journalism and Communication	F	FARG	G	743	A	t	f	87	f
749	A0	Journalism and Communication	F	FARG	G	1859	A	t	f	87	f
750	A0	Land Administration and Management	F	FARG	G	590	A	t	f	87	f
751	A0	Land Administration and Management	F	FARG	G	595	A	t	f	87	f
752	A0	Management/ Accounting	F	FARG	G	592	A	t	f	87	f
753	A0	Management/ Accounting	F	FARG	G	1897	A	t	f	87	f
754	A0	Marketing	F	FARG	G	2504	A	t	f	87	f
755	A0	Marketing	F	FARG	G	1533	A	t	f	87	f
756	A0	Marketing	F	FARG	G	2029	A	t	f	87	f
757	A0	Medicine	F	FARG	G	2465	A	t	f	87	f
758	A0		F	FARG	G	1981	A	t	f	87	f
759	A0	political science	F	FARG	G	2510	A	t	f	87	f
760	A0	Public Administration and Good Governance	F	FARG	G	2070	A	t	f	87	f
761	A0	Public Administration and Good Governance	F	FARG	G	1800	A	t	f	87	f
762	A0	social worker	F	FARG	G	1976	A	t	f	87	f
763	A0	social worker	F	FARG	G	2267	A	t	f	87	f
764	A0	Translation and Intepretation	F	FARG	G	2394	A	t	f	87	f
765	A0	Social Worker	F	FARG	O	806	A	t	f	87	f
766	A0	Finance	F	FARG and These Number have faces	G	2015	A	t	f	87	f
767	A0	Finance	S	Private sponsor	D	2366	A	t	f	87	f
768	A0	Economic	S	Private sponsor	G	804	A	t	f	87	f
769	A0	Education	S	Private sponsor	G	1597	A	t	f	87	f
770	A0	Education	S	Private sponsor	G	2240	A	t	f	87	f
771	A0	Finance	S	Private sponsor	G	2223	A	t	f	87	f
772	A0		S	Private sponsor	G	2013	A	t	f	87	f
773	A0		S	Private sponsor	G	1634	A	t	f	87	f
774	A0		S	Private sponsor	G	2463	A	t	f	87	f
775	A0	Agroforestry	S	Private sponsor	O	1473	A	t	f	87	f
776	A0	BSC Accounting	S	Private sponsor	O	1905	A	t	f	87	f
777	A0	Computer and business	S	Private sponsor	O	2246	A	t	f	87	f
778	A0	Education	S	Private sponsor	O	2177	A	t	f	87	f
779	A0	Finance	S	Private sponsor	O	2050	A	t	f	87	f
780	A0	Information System	S	Private sponsor	O	2497	A	t	f	87	f
781	A0		S	Private sponsor	O	1856	A	t	f	87	f
782	A0	Statistic	S	Private sponsor	O	1997	A	t	f	87	f
783	A0	Agri-Business	S	Private sponsor	G	2071	A	t	f	87	f
784	A0	Construction Management	S	Private sponsor	G	1701	A	t	f	87	f
785	A0	CPA	S	Private sponsor	G	1794	A	t	f	87	f
786	A0	Finance	S	Private sponsor	G	1521	A	t	f	87	f
787	A0	Information Communication and Technology	S	Private sponsor	G	2329	A	t	f	87	f
788	A0	Social Worker	S	Private sponsor	G	2280	A	t	f	87	f
789	A0	Accounting	S	Private sponsor	O	1940	A	t	f	87	f
790	A0	Accounting	F	REB	G	1988	A	t	f	87	f
791	A0	Accounting	F	REB	G	1883	A	t	f	87	f
792	A0	Accounting	F	REB	G	2119	A	t	f	87	f
793	A0	Accounting	F	REB	G	2535	A	t	f	87	f
794	A0	Accounting	F	REB	G	1563	A	t	f	87	f
795	A0	Accounting	F	REB	G	145	A	t	f	87	f
796	A0	Accounting	F	REB	G	2526	A	t	f	87	f
797	A0	Accounting	F	REB	G	1699	A	t	f	87	f
798	A0	Agri-business	F	REB	G	58	A	t	f	87	f
799	A0	Agriculture	F	REB	G	1889	A	t	f	87	f
800	A0	Bio-Medical Laboratory	F	REB	G	1546	A	t	f	87	f
801	A0	Bio-Technology	F	REB	G	2263	A	t	f	87	f
802	A0	Bio-Technology	F	REB	G	2053	A	t	f	87	f
803	A0	Biology	F	REB	G	1957	A	t	f	87	f
804	A0	Business Information and Technology	F	REB	G	2101	A	t	f	87	f
805	A0	Business Information and Technology	F	REB	G	1751	A	t	f	87	f
806	A0	Business Information and Technology	F	REB	G	2527	A	t	f	87	f
807	A0	Business Information and Technology	F	REB	G	1641	A	t	f	87	f
808	A0	Business Information and Technology	F	REB	G	2002	A	t	f	87	f
809	M	Business Information and Technology	F	REB	G	1767	A	t	f	87	f
810	A0	Business Information and Technology	F	REB	G	1675	A	t	f	87	f
811	A0	Business Management and Entrepreneurship	F	REB	G	2276	A	t	f	87	f
812	A0	Civil Engineering	F	REB	G	1944	A	t	f	87	f
813	A0	Civil Engineering	F	REB	G	2052	A	t	f	87	f
814	A0	Civil engineering option water Resources	F	REB	G	93	A	t	f	87	f
815	A0	Computer and Networking Engineering	F	REB	G	2157	A	t	f	87	f
816	A0	Computer and Software Engineering	F	REB	G	1498	A	t	f	87	f
817	A0	computer and software Engineering	F	REB	G	1579	A	t	f	87	f
818	A0	Computer Science	F	REB	G	120	A	t	f	87	f
819	A0	Computer Science	F	REB	G	1540	A	t	f	87	f
820	A0	Computer Science	F	REB	G	1958	A	t	f	87	f
821	M	Computer Science	F	REB	G	1716	A	t	f	87	f
822	A0	Construction Management	F	REB	G	157	A	t	f	87	f
823	A0	Dentist	F	REB	G	166	A	t	f	87	f
824	A0	Economic	F	REB	G	1524	A	t	f	87	f
825	A0	Economic	F	REB	G	1837	A	t	f	87	f
826	A0	Economic	F	REB	G	2194	A	t	f	87	f
827	A0	Economic	F	REB	G	2146	A	t	f	87	f
828	A0	Economic	F	REB	G	609	A	t	f	87	f
829	A0	Economic	F	REB	G	1921	A	t	f	87	f
830	A0	Economic	F	REB	G	1655	A	t	f	87	f
831	A0	Economic	F	REB	G	2524	A	t	f	87	f
832	A0	Education	F	REB	G	11	A	t	f	87	f
833	M	Electronic Engineering	F	REB	G	1581	A	t	f	87	f
834	A0	Estatant Management and  Evaluation	F	REB	G	577	A	t	f	87	f
835	A0	Finance	F	REB	G	168	A	t	f	87	f
836	A0	Finance	F	REB	G	573	A	t	f	87	f
837	A0	Finance	F	REB	G	582	A	t	f	87	f
838	A0	Finance	F	REB	G	613	A	t	f	87	f
839	A0	Finance	F	REB	G	1517	A	t	f	87	f
840	A0	finance	F	REB	G	1740	A	t	f	87	f
841	A0	Finance	F	REB	G	1575	A	t	f	87	f
842	A0	Finance	F	REB	G	144	A	t	f	87	f
843	A0	Finance	F	REB	G	739	A	t	f	87	f
844	A0	Finance	F	REB	G	1626	A	t	f	87	f
845	A0	Finance	F	REB	G	49	A	t	f	87	f
846	A0	Finance	F	REB	G	2294	A	t	f	87	f
847	A0	Finance	F	REB	G	2023	A	t	f	87	f
848	A0	General Nursing	F	REB	G	2148	A	t	f	87	f
849	A0	Geography	F	REB	G	2161	A	t	f	87	f
850	A0	Geography	F	REB	G	1994	A	t	f	87	f
851	A0	Geography	F	REB	G	1501	A	t	f	87	f
852	A0	Human Ressource Management	F	REB	G	2030	A	t	f	87	f
853	A0	Information Communication and Technology	F	REB	G	1638	A	t	f	87	f
854	A0	Information Communication and Technology	F	REB	G	2257	A	t	f	87	f
855	A0	Information Technology	F	REB	G	121	A	t	f	87	f
856	A0	Information Technology	F	REB	G	2192	A	t	f	87	f
857	A0	Information Technology	F	REB	G	40	A	t	f	87	f
858	A0	Information Technology Engineering	F	REB	G	2286	A	t	f	87	f
859	A0	Information Technology Engineering	F	REB	G	2113	A	t	f	87	f
860	A0	International Economics	F	REB	G	2243	A	t	f	87	f
861	A0	Journalism and Communication	F	REB	G	719	A	t	f	87	f
862	A0	Journalism and Communication	F	REB	G	726	A	t	f	87	f
863	A0	Journalism and Communication	F	REB	G	2430	A	t	f	87	f
864	A0	Journalism and Communication	F	REB	G	1902	A	t	f	87	f
865	A0	Journalism and Communication	F	REB	G	2423	A	t	f	87	f
866	A0	Journalism and Communication	F	REB	G	2060	A	t	f	87	f
867	A0	Journalism and Communication	F	REB	G	1451	A	t	f	87	f
868	A0	Laboratory	F	REB	G	1710	A	t	f	87	f
869	A0	Marketing	F	REB	G	1637	A	t	f	87	f
870	A0	Marketing	F	REB	G	2506	A	t	f	87	f
871	A0	Mathematic	F	REB	G	1928	A	t	f	87	f
872	A0	Medical Imaging Sciences	F	REB	G	610	A	t	f	87	f
939	A0	Accounting	F	FARG	G	2467	A	t	f	88	f
873	A0	Missed Information	F	REB	G	2104	A	t	f	87	f
874	A0	Procument Management	F	REB	G	109	A	t	f	87	f
875	A0	Procument Management	F	REB	G	29	A	t	f	87	f
876	A0	Procument Management	F	REB	G	586	A	t	f	87	f
877	A0	Procument Management	F	REB	G	710	A	t	f	87	f
878	A0	Procument Management	F	REB	G	1615	A	t	f	87	f
879	A0	Social Worker	F	REB	G	2147	A	t	f	87	f
880	A0	Statistic	F	REB	G	108	A	t	f	87	f
881	A0	Statistic	F	REB	G	1812	A	t	f	87	f
882	A0	Water and Environment Engineering	F	REB	G	113	A	t	f	87	f
883	A0	Economic	F	REB	G	1881	A	t	f	87	f
884	A0	Accounting	F	REB	O	1871	A	t	f	87	f
885	A0	Accounting	F	REB	O	1830	A	t	f	87	f
886	A0	Agriculture	F	REB	O	100	A	t	f	87	f
887	A0	Clinical Medical	F	REB	O	2293	A	t	f	87	f
888	A0	Computer Science	F	REB	O	2357	A	t	f	87	f
889	A0	Demography applied to Statistics	F	REB	O	1558	A	t	f	87	f
890	A0	Development studies	F	REB	O	2027	A	t	f	87	f
891	A0	Economic	F	REB	O	699	A	t	f	87	f
892	A0	Economic	F	REB	O	704	A	t	f	87	f
893	A0	Economic	F	REB	O	2020	A	t	f	87	f
894	A0	Economic	F	REB	O	1813	A	t	f	87	f
895	A0	Education	F	REB	O	1545	A	t	f	87	f
896	A0	Information System	F	REB	O	713	A	t	f	87	f
897	A0	Information Technology	F	REB	O	701	A	t	f	87	f
898	A0	Economic	F	Safilife Foundation	G	2488	A	t	f	87	f
899	A0	Business Information and Technology	F	University Scholarship	G	1632	A	t	f	87	f
900	A0	Business Information and Technology	F	University Scholarship	G	2207	A	t	f	87	f
901	A1	Business Management and Entrepreneurship	F	University Scholarship	G	796	A	t	f	87	f
902	A0	Finance	F	University Scholarship	G	1515	A	t	f	87	f
903	A0	Hospitality Management	F	University Scholarship	G	165	A	t	f	87	f
904	A0	Hospitality Management	F	University Scholarship	G	2184	A	t	f	87	f
905	A0	Hospitality Management	F	University Scholarship	G	2365	A	t	f	87	f
906	A0	International Economics	F	University Scholarship	G	702	A	t	f	87	f
907	A0	Agriculture	F	university Scholarship	O	1971	A	t	f	87	f
908	A0	Agriculture	F	University Scholarship	O	1744	A	t	f	87	f
909	A0	Applied Statistic and Demography	F	university Scholarship	O	2074	A	t	f	87	f
910	A0	Business and Economic	F	university Scholarship	O	2372	A	t	f	87	f
911	A0	Computer Engineering	F	university Scholarship	O	2473	A	t	f	87	f
912	A0	Economic	F	University Scholarship	O	2234	A	t	f	87	f
913	A0	Governance and Leardership	F	university Scholarship	O	2351	A	t	f	87	f
914	A0	Human Ressource	F	university Scholarship	O	2290	A	t	f	87	f
915	A0	IT Training/Programing	F	University Scholarship	O	2369	A	t	f	87	f
916	A0	Law	F	university Scholarship	O	1727	A	t	f	87	f
917	A0	Linguistic and Languages	F	University Scholarship	O	1752	A	t	f	87	f
918	A0	Accounting and Finance	F	University Scholarship	O	73	A	t	f	87	f
919	A0	Accounting and finance	F	University Scholarship	O	672	A	t	f	87	f
920	A0	Accounting and finance administration management	F	University Scholarship	O	2018	A	t	f	87	f
921	A0	Advanced diploma in nursing	F	University Scholarship	O	1870	A	t	f	87	f
922	A0	business and economics	F	University Scholarship	O	1965	A	t	f	87	f
923	A0	Economic	F	University Scholarship	O	1591	A	t	f	87	f
924	A0	Economic	F	University Scholarship	O	1885	A	t	f	87	f
925	A0	History and Heritage	F	University Scholarship	O	676	A	t	f	87	f
926	A0	Quantitan Survey	F	University Scholarship	O	677	A	t	f	87	f
927	A0	Transport and Logistic	F	University Scholarship	O	1510	A	t	f	87	f
928	A0	Water and Environment Engineering	F	University Scholarship	O	1844	A	t	f	87	f
929	A0	Water and Environment Engineering	F	University Scholarship	O	2065	A	t	f	87	f
930	A0	Water and Environment Engineering	F	University Scholarship	O	2135	A	t	f	87	f
931	A0	Water and Environment Engineering	F	University Scholarship	O	2421	A	t	f	87	f
932	A0	Water and Environment Engineering	F	University Scholarship	O	1673	A	t	f	87	f
933	A0	Water and Environment Engineering	F	University Scholarship	O	1893	A	t	f	87	f
934	A0	Water and Environment Engineering	F	University Scholarship	O	2292	A	t	f	87	f
935	A0	Water and Environment Engineering	F	University Scholarship	O	1833	A	t	f	87	f
936	A0	Water and Environment Engineering	F	University Scholarship	O	1936	A	t	f	87	f
937	A0	Water and Environment Engineering	F	University Scholarship	O	2058	A	t	f	87	f
938	C	CPA	F	University Scholarship	G	1767	A	f	f	87	f
940	A0	Hospitality Management	F	FARG	G	604	A	t	f	88	f
941	A0	Hospitality Management	F	FARG	G	605	A	t	f	88	f
942	A0	Hospitality Management	F	FARG	G	1781	A	t	f	88	f
943	A0	Information Communication and Technology	F	FARG	G	1541	A	t	f	88	f
944	A0	Marketing	F	FARG	G	142	A	t	f	88	f
945	A0	Travel and Tourism Management	F	FARG	G	2272	A	t	f	88	f
946	A0	Travel and Tourism Management	F	FARG	G	2519	A	t	f	88	f
947	A0	Travel and Tourism Management	F	FARG	G	1539	A	t	f	88	f
948	A0	Travel and Tourism Management	F	FARG	G	2478	A	t	f	88	f
949	A0	Travel and Tourism Management	F	FARG	G	1490	A	t	f	88	f
950	A1	Hospitality and Management	S	Private sponsor	G	1601	A	t	f	88	f
951	A0	Marketing	S	Private sponsor	G	1760	A	t	f	88	f
952	A0	Marketing	S	Private sponsor	G	705	A	t	f	88	f
953	A0	Accounting	S	Private sponsor	O	1875	A	t	f	88	f
954	A0	Travet and Tourism Management	S	Private sponsor	O	2353	A	t	f	88	f
955	A0	Accounting	S	Private sponsor	G	68	A	t	f	88	f
956	A0	Business Information and Technology	S	Private sponsor	G	585	A	t	f	88	f
957	A0	Food production and hospitality	S	Private sponsor	G	1611	A	t	f	88	f
958	A0	Hospitality Management	S	Private sponsor	G	718	A	t	f	88	f
959	A0	Hospitality Management	S	Private sponsor	G	2311	A	t	f	88	f
960	A0	Hospitality Management	S	Private sponsor	G	1627	A	t	f	88	f
961	A0	Hospitality Management	S	Private sponsor	G	2349	A	t	f	88	f
962	A0	Hospitality Management	S	Private sponsor	G	2051	A	t	f	88	f
963	A0	Hospitality Management	S	Private sponsor	G	1713	A	t	f	88	f
964	A0	Hospitality Management	S	Private sponsor	G	1887	A	t	f	88	f
965	A0	Hospitality Management	S	Private sponsor	G	1968	A	t	f	88	f
966	A0	Logistic	S	Private sponsor	G	2159	A	t	f	88	f
967	A0	Marketing	S	Private sponsor	G	2045	A	t	f	88	f
968	A0	Tourism Management	S	Private sponsor	G	1562	A	t	f	88	f
969	A0	Travel and Tourism Management	S	Private sponsor	G	616	A	t	f	88	f
970	A0	Travel and Tourism Management	S	Private sponsor	G	2368	A	t	f	88	f
971	A0	Travel and Tourism Management	S	Private sponsor	G	1573	A	t	f	88	f
972	A0	Travel and Tourism Management	S	Private sponsor	G	764	A	t	f	88	f
973	A0	Travel and Tourism Management	S	Private sponsor	G	1886	A	t	f	88	f
974	A0	Main Tourism and Hotel Management	S	Private sponsor	O	1848	A	t	f	88	f
975	A0	Tourism Management	S	Private sponsor	O	2174	A	t	f	88	f
976	A0	Business and Information Technology	F	REB	G	698	A	t	f	88	f
977	A0	Economic	F	REB	G	2345	A	t	f	88	f
978	A0	Main Tourism and Hotel Management	F	university Scholarship	O	1847	A	t	f	88	f
979	A0	Travel Management	F	University Scholarship	O	2382	A	t	f	88	f
980	A0	Business Management	S	Private sponsor	O	1832	A	t	f	89	f
981	A0	Information System	F	University Scholarship	O	1459	A	t	f	90	f
982	A0	International Hotel Management	F	Mastercard	G	60	A	t	f	91	f
983	A0	International Hotel Management	F	Mastercard	G	22	A	t	f	91	f
984	A0	International Hotel Management	F	Mastercard	G	746	A	t	f	91	f
985	A0	International Hotel Management	F	Mastercard	G	751	A	t	f	91	f
986	A0	International Hotel Management	F	Mastercard	G	758	A	t	f	91	f
987	A0	International Hotel Management	F	Mastercard	G	1696	A	t	f	91	f
988	A0	International Hotel Management	F	Mastercard	G	1807	A	t	f	91	f
989	A0	Hospitality Management	S	Private sponsor	G	2248	A	t	f	91	f
990	A0	International Hotel Management	F	University Scholarship	G	50	A	t	f	91	f
991	A0	International Hotel Management	F	University Scholarship	G	2046	A	t	f	91	f
992	A0	International Hotel Management	F	University Scholarship	G	1588	A	t	f	91	f
993	A0	International Hotel Management	F	University Scholarship	G	2054	A	t	f	91	f
994	A0	International Hotel Management	F	University Scholarship	G	805	A	t	f	91	f
995	A0	International Hotel Management	F	University Scholarship	G	1714	A	t	f	91	f
996	A0	Economic	S	Private sponsor	O	2131	A	t	f	92	f
997	A0	Economic	F	University Scholarship	O	2424	A	t	f	93	f
998	A0	Busines Management  and Computer Science	F	University Scholarship	O	2235	A	t	f	94	f
999	M	Senior Client Service representantive	F	REB	G	111	A	t	f	95	f
1000	M	International Hotel Management	F	University Scholarship	G	1594	A	t	f	95	f
1001	A0	Senior Client Service representantive	F	University Scholarship	O	1703	A	t	f	96	f
\.


--
-- TOC entry 3414 (class 0 OID 0)
-- Dependencies: 253
-- Name: api_furthereducation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_furthereducation_id_seq', 1001, true);


--
-- TOC entry 3262 (class 2606 OID 68752)
-- Name: api_furthereducation api_furthereducation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_furthereducation
    ADD CONSTRAINT api_furthereducation_pkey PRIMARY KEY (id);


--
-- TOC entry 3259 (class 1259 OID 68785)
-- Name: api_furthereducation_alumn_id_3a17dea5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_furthereducation_alumn_id_3a17dea5 ON public.api_furthereducation USING btree (alumn_id);


--
-- TOC entry 3260 (class 1259 OID 68831)
-- Name: api_furthereducation_college_id_0e3a5db0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_furthereducation_college_id_0e3a5db0 ON public.api_furthereducation USING btree (college_id);


--
-- TOC entry 3263 (class 2606 OID 68821)
-- Name: api_furthereducation api_furthereducation_alumn_id_3a17dea5_fk_api_kid_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_furthereducation
    ADD CONSTRAINT api_furthereducation_alumn_id_3a17dea5_fk_api_kid_id FOREIGN KEY (alumn_id) REFERENCES public.api_kid(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3264 (class 2606 OID 76920)
-- Name: api_furthereducation api_furthereducation_college_id_0e3a5db0_fk_api_college_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_furthereducation
    ADD CONSTRAINT api_furthereducation_college_id_0e3a5db0_fk_api_college_id FOREIGN KEY (college_id) REFERENCES public.api_college(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-06-04 16:46:41

--
-- PostgreSQL database dump complete
--

