--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2025-05-28 16:42:59

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 246 (class 1259 OID 52292)
-- Name: api_kidacademics; Type: TABLE; Schema: public; Owner: postgres
--

DROP TABLE IF EXISTS public.api_kidacademics;

CREATE TABLE public.api_kidacademics (
    id bigint NOT NULL,
    academic_year integer NOT NULL,
    combination_id bigint NOT NULL,
    kid_id bigint NOT NULL,
    level character varying(10) NOT NULL
);


ALTER TABLE public.api_kidacademics OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 52291)
-- Name: api_kidacademics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_kidacademics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_kidacademics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3410 (class 0 OID 52292)
-- Dependencies: 246
-- Data for Name: api_kidacademics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_kidacademics (id, academic_year, combination_id, kid_id, level) FROM stdin;
1	2014	7	573	S6
2	2013	7	573	S5
3	2012	7	573	S4
\.


--
-- TOC entry 3416 (class 0 OID 0)
-- Dependencies: 245
-- Name: api_kidacademics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_kidacademics_id_seq', 3, true);


--
-- TOC entry 3262 (class 2606 OID 52310)
-- Name: api_kidacademics api_kidacademics_kid_id_academic_year_bf456834_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_kidacademics
    ADD CONSTRAINT api_kidacademics_kid_id_academic_year_bf456834_uniq UNIQUE (kid_id, academic_year);


--
-- TOC entry 3264 (class 2606 OID 52296)
-- Name: api_kidacademics api_kidacademics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_kidacademics
    ADD CONSTRAINT api_kidacademics_pkey PRIMARY KEY (id);


--
-- TOC entry 3259 (class 1259 OID 52326)
-- Name: api_kidacademics_combination_id_c7576007; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_kidacademics_combination_id_c7576007 ON public.api_kidacademics USING btree (combination_id);


--
-- TOC entry 3260 (class 1259 OID 52327)
-- Name: api_kidacademics_kid_id_7b199f02; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_kidacademics_kid_id_7b199f02 ON public.api_kidacademics USING btree (kid_id);


--
-- TOC entry 3265 (class 2606 OID 52311)
-- Name: api_kidacademics api_kidacademics_combination_id_c7576007_fk_api_combination_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_kidacademics
    ADD CONSTRAINT api_kidacademics_combination_id_c7576007_fk_api_combination_id FOREIGN KEY (combination_id) REFERENCES public.api_combination(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3266 (class 2606 OID 52316)
-- Name: api_kidacademics api_kidacademics_kid_id_7b199f02_fk_api_kid_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_kidacademics
    ADD CONSTRAINT api_kidacademics_kid_id_7b199f02_fk_api_kid_id FOREIGN KEY (kid_id) REFERENCES public.api_kid(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-05-28 16:42:59

--
-- PostgreSQL database dump complete
--

